import type { Question } from "@/types";

/**
 * HADITH QUESTIONS — legitimate sources only.
 * Convention: cite book + exact hadith number, following the standard sunnah.com
 * numbering (standard Arabic editions / Dar-us-Salam English translation).
 * Numbers verified against sunnah.com in Aug 2026. "Agreed upon" = in both
 * Sahih al-Bukhari and Sahih Muslim. Only narrations from well-known authentic
 * collections are used.
 */
export const hadithQuestions: Question[] = [
  // ---- Newbie ----
  {
    id: "hadith-001",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 1,
    prompt: "According to the well-known hadith, 'Actions are but by...' what?",
    arabic: "إنما الأعمال بالنيات",
    options: ["Intention", "Speech", "Wealth", "Force"],
    answerIndex: 0,
    explanation:
      "The hadith 'Actions are but by intentions, and every person will have only what they intended' is reported from Umar ibn al-Khattab and is agreed upon in Bukhari and Muslim.",
    source: "Sahih al-Bukhari 1 & Sahih Muslim 1907, from Umar ibn al-Khattab",
    confidence: "high",
  },
  {
    id: "hadith-002",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 1,
    prompt: "According to the hadith, Islam is built upon how many pillars?",
    options: ["Five", "Three", "Seven", "Four"],
    answerIndex: 0,
    explanation:
      "The agreed-upon hadith from Ibn Umar lists the pillars of Islam as the two testimonies, prayer, charity (zakat), fasting Ramadan, and the pilgrimage (Hajj).",
    source: "Sahih al-Bukhari 8 & Sahih Muslim 16, from Abdullah ibn Umar",
    confidence: "high",
  },
  {
    id: "hadith-003",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 2,
    prompt: "Complete the hadith: 'The best of you are those who...'",
    options: [
      "Learn the Quran and teach it",
      "Pray the most at night",
      "Fast most often",
      "Give the most charity",
    ],
    answerIndex: 0,
    explanation:
      "Reported by Uthman ibn Affan: 'The best of you are those who learn the Quran and teach it.' Narrated in Sahih al-Bukhari.",
    source: "Sahih al-Bukhari 5027, from Uthman ibn Affan",
    confidence: "high",
  },
  {
    id: "hadith-004",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 2,
    prompt: "Complete the hadith: 'None of you truly believes until he loves for his brother what...'",
    options: [
      "He loves for himself",
      "His brother loves for him",
      "He has worked for",
      "He asks for in prayer",
    ],
    answerIndex: 0,
    explanation:
      "The agreed-upon hadith states that complete faith includes loving for your brother what you love for yourself. Narrated from Anas ibn Malik.",
    source: "Sahih al-Bukhari 13 & Sahih Muslim 45, from Anas ibn Malik",
    confidence: "high",
  },
  {
    id: "hadith-005",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 2,
    prompt: "What does the hadith 'Purification is half of...' refer to?",
    options: ["Faith", "Prayer", "Charity", "Patience"],
    answerIndex: 0,
    explanation:
      "'Purification is half of faith' is reported from Abu Malik al-Ash'ari in Sahih Muslim, highlighting the value of cleanliness and wudu.",
    source: "Sahih Muslim 223, from Abu Malik al-Ash'ari",
    confidence: "high",
  },
  {
    id: "hadith-006",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 2,
    prompt: "Complete the hadith: 'Whoever believes in Allah and the Last Day should speak good or...'",
    options: ["Remain silent", "Leave the gathering", "Apologize", "Repeat it twice"],
    answerIndex: 0,
    explanation:
      "The agreed-upon hadith from Abu Hurayrah instructs believers to speak good or remain silent, and also to honor their guest and neighbor.",
    source: "Sahih al-Bukhari 6018 & Sahih Muslim 47, from Abu Hurayrah",
    confidence: "high",
  },
  {
    id: "hadith-007",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 1,
    prompt: "Which quality did the Prophet describe as 'part of faith'?",
    options: ["Modesty", "Strength", "Wealth", "Eloquence"],
    answerIndex: 0,
    explanation:
      "The agreed-upon hadith from Ibn Umar states: 'Modesty is part of faith.' Modesty here includes both bashfulness and moral restraint.",
    source: "Sahih al-Bukhari 24 & Sahih Muslim 36, from Abdullah ibn Umar",
    confidence: "high",
  },

  // ---- Average ----
  {
    id: "hadith-008",
    pillar: "hadith",
    tier: "average",
    difficulty: 3,
    prompt: "The hadith describes fasting as what?",
    options: ["A shield", "A burden", "A reward in full", "A private act"],
    answerIndex: 0,
    explanation:
      "'Fasting is a shield' is the agreed-upon hadith from Abu Hurayrah — fasting protects the believer from sin as a shield protects in battle.",
    source: "Sahih al-Bukhari 1894 & Sahih Muslim 1151, from Abu Hurayrah",
    confidence: "high",
  },
  {
    id: "hadith-009",
    pillar: "hadith",
    tier: "average",
    difficulty: 3,
    prompt: "What is the reward mentioned for whoever fasts Ramadan out of faith and seeking reward?",
    options: [
      "Their past sins are forgiven",
      "They are granted Paradise without account",
      "Their status rises one level",
      "They are freed from all trials",
    ],
    answerIndex: 0,
    explanation:
      "The agreed-upon hadith from Abu Hurayrah says: 'Whoever fasts Ramadan out of faith and seeking reward, his past sins will be forgiven.'",
    source: "Sahih al-Bukhari 38 & Sahih Muslim 760, from Abu Hurayrah",
    confidence: "high",
  },
  {
    id: "hadith-010",
    pillar: "hadith",
    tier: "average",
    difficulty: 3,
    prompt: "Complete the hadith: 'The most complete of believers in faith are those who have the best...'",
    options: ["Character", "Knowledge", "Recitation", "Memory"],
    answerIndex: 0,
    explanation:
      "Reported by Abu Hurayrah in at-Tirmidhi (graded hasan): 'The most complete of believers in faith are those with the best character.'",
    source: "Jami' at-Tirmidhi 2612 (graded hasan), from Abu Hurayrah",
    confidence: "high",
  },
  {
    id: "hadith-011",
    pillar: "hadith",
    tier: "average",
    difficulty: 3,
    prompt: "What does Allah do, according to the hadith, for the one who takes a path seeking knowledge?",
    options: [
      "Eases a path to Paradise for them",
      "Gives them wealth",
      "Makes them a leader of people",
      "Answers all their supplications",
    ],
    answerIndex: 0,
    explanation:
      "Sahih Muslim reports: 'Whoever takes a path seeking knowledge, Allah eases for them a path to Paradise.'",
    source: "Sahih Muslim 2699, from Abu Hurayrah",
    confidence: "high",
  },
  {
    id: "hadith-012",
    pillar: "hadith",
    tier: "average",
    difficulty: 3,
    prompt: "The believer who recites the Quran is likened to which fruit in the agreed-upon hadith?",
    options: ["A citron", "A date", "A pomegranate", "A grape"],
    answerIndex: 0,
    explanation:
      "The agreed-upon hadith from Abu Musa likens the believer who recites the Quran to a citron (utrujjah) — pleasant in smell and taste.",
    source: "Sahih al-Bukhari 5020 & Sahih Muslim 797, from Abu Musa al-Ash'ari",
    confidence: "high",
  },
  {
    id: "hadith-013",
    pillar: "hadith",
    tier: "average",
    difficulty: 3,
    prompt: "How did the Prophet describe entry into Paradise by deeds alone?",
    options: [
      "No one enters by deeds alone, but by Allah's mercy",
      "Everyone is admitted by their deeds",
      "Only the scholars enter by their deeds",
      "Deeds are irrelevant on that day",
    ],
    answerIndex: 0,
    explanation:
      "The agreed-upon hadith from Abu Hurayrah: 'No one will enter Paradise by his deeds alone.' They said, 'Not even you, O Messenger of Allah?' He said, 'Not even me, except that Allah envelops me in His mercy.'",
    source: "Sahih al-Bukhari 5673 & Sahih Muslim 2816, from Abu Hurayrah",
    confidence: "high",
  },
  {
    id: "hadith-014",
    pillar: "hadith",
    tier: "average",
    difficulty: 3,
    prompt: "According to Sahih Muslim, the five daily prayers and Friday-to-Friday expiate sins between them — with what condition?",
    options: [
      "So long as major sins are avoided",
      "That one attends the mosque for every prayer",
      "That one recites specific supplications",
      "That one gives charity each week",
    ],
    answerIndex: 0,
    explanation:
      "The hadith from Abu Hurayrah states the daily prayers and Fridays expiate sins between them 'so long as major sins are avoided.'",
    source: "Sahih Muslim 233, from Abu Hurayrah",
    confidence: "high",
  },

  // ---- Intermediate ----
  {
    id: "hadith-015",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 4,
    prompt: "In the famous hadith of Jibril, the angel asked the Prophet about which three things, in addition to the Hour?",
    options: ["Islam, Iman, and Ihsan", "Prayer, charity, and fasting", "Faith, patience, and gratitude", "Hajj, zakat, and jihad"],
    answerIndex: 0,
    explanation:
      "In the hadith of Jibril (reported in Sahih Muslim from Umar), the angel asked about Islam (submission), Iman (faith), and Ihsan (excellence), then about the signs of the Hour.",
    source: "Sahih Muslim 8, from Umar ibn al-Khattab",
    confidence: "high",
  },
  {
    id: "hadith-016",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 4,
    prompt: "When asked which deeds are most beloved to Allah, what did the Prophet say, according to the agreed-upon hadith from Aisha?",
    options: [
      "The most consistent, even if small",
      "The greatest in quantity",
      "Those done in the mosque",
      "Those done in secret",
    ],
    answerIndex: 0,
    explanation:
      "The agreed-upon hadith from Aisha: the most beloved deeds to Allah are those done consistently, even if they are small.",
    source: "Sahih al-Bukhari 6464 & Sahih Muslim 783, from Aisha",
    confidence: "high",
  },
  {
    id: "hadith-017",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 4,
    prompt: "In the agreed-upon hadith, how many branches does faith have, with the highest being 'La ilaha illallah'?",
    options: ["Seventy-odd branches", "Exactly fifty", "Ninety-nine", "A hundred and one"],
    answerIndex: 0,
    explanation:
      "The agreed-upon hadith from Abu Hurayrah states faith has 'seventy-odd branches'; the highest is saying there is no god but Allah, and the lowest is removing harm from the path.",
    source: "Sahih al-Bukhari 9 & Sahih Muslim 35, from Abu Hurayrah",
    confidence: "high",
  },
  {
    id: "hadith-018",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 5,
    prompt: "In the hadith of the Two Weighty Things (ath-Thaqalayn), what did the Prophet leave behind as a guide?",
    options: [
      "The Book of Allah and his family (Ahl al-Bayt)",
      "The Quran and the Sunnah only",
      "His companions and the Quran",
      "The Mosque and the Scholars",
    ],
    answerIndex: 0,
    explanation:
      "Reported in Sahih Muslim from Zayd ibn Arqam, the Prophet said he leaves among the people two weighty things: the Book of Allah and his family (Ahl al-Bayt).",
    source: "Sahih Muslim 2408 (Fada'il al-Sahaba), from Zayd ibn Arqam",
    confidence: "high",
  },
  {
    id: "hadith-019",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 5,
    prompt: "According to Sahih Muslim, the one who dies without having given what is described as dying a death of ignorance?",
    options: ["Bay'ah (allegiance to the leader)", "Zakat (charity)", "Hajj (pilgrimage)", "Jihad (struggle)"],
    answerIndex: 0,
    explanation:
      "The hadith from Ibn Umar states: 'Whoever dies having not given bay'ah dies a death of jahiliyyah' — highlighting the importance of unity under leadership.",
    source: "Sahih Muslim 1851, from Abdullah ibn Umar",
    confidence: "high",
  },
  {
    id: "hadith-020",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 4,
    prompt: "How does Sahih Muslim describe the strong believer compared to the weak believer?",
    options: [
      "Better and more beloved to Allah, though there is good in both",
      "More fortunate in this world only",
      "Equal in the sight of Allah",
      "More likely to enter Paradise directly",
    ],
    answerIndex: 0,
    explanation:
      "Sahih Muslim (from Abu Hurayrah): 'The strong believer is better and more beloved to Allah than the weak believer, though there is good in both.' The hadith then advises seeking what benefits and relying on Allah.",
    source: "Sahih Muslim 2664, from Abu Hurayrah",
    confidence: "high",
  },
  {
    id: "hadith-021",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 4,
    prompt: "According to Sahih Muslim, Allah continues to help His servant as long as the servant does what?",
    options: [
      "Helps his brother",
      "Prays in congregation",
      "Gives charity weekly",
      "Recites the Quran daily",
    ],
    answerIndex: 0,
    explanation:
      "Sahih Muslim (from Abu Hurayrah): 'Allah is in the help of the servant as long as the servant is in the help of his brother.'",
    source: "Sahih Muslim 2699, from Abu Hurayrah",
    confidence: "high",
  },

  // ---- Newbie expansion (numbers verified vs sunnah.com, Aug 2026) ----
  {
    id: "hadith-022",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 2,
    prompt: "According to a hadith, who is the truly strong person?",
    options: [
      "The one who controls himself when angry",
      "The one who can wrestle others",
      "The one who lifts the greatest weights",
      "The one who never tires",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'The strong person is not the one who can wrestle; rather, the strong person is the one who controls himself when angry.'",
    source: "Sahih al-Bukhari 6114, from Abu Hurayrah",
    confidence: "high",
  },
  {
    id: "hadith-023",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 2,
    prompt: "According to a hadith, which two blessings do many people squander?",
    options: ["Health and free time", "Wealth and children", "Knowledge and fame", "Food and shelter"],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'There are two blessings that many people squander: health and free time.' It urges using both for good deeds before they are lost.",
    source: "Sahih al-Bukhari 6412, from Ibn Abbas",
    confidence: "high",
  },
  {
    id: "hadith-024",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 2,
    prompt: "In the hadith, the believers, in their mercy and affection, are likened to —",
    options: ["One body", "A fortress", "A flock of birds", "A field of wheat"],
    answerIndex: 0,
    explanation:
      "The Prophet likened the believers to one body: if one part suffers, the whole body shares the fever and sleeplessness. It teaches mutual care.",
    source: "Sahih al-Bukhari 6011, from An-Nu'man ibn Bashir",
    confidence: "high",
  },

  // ---- Average expansion ----
  {
    id: "hadith-025",
    pillar: "hadith",
    tier: "average",
    difficulty: 3,
    prompt: "In the hadith of An-Nu'man ibn Bashir, between what is clearly halal and clearly haram lie —",
    options: [
      "Doubtful matters (ash-shubuhat)",
      "Silent sins",
      "Minor mistakes",
      "Recommended acts",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said what is lawful is clear and what is unlawful is clear, and between them are doubtful matters. Whoever avoids the doubtful protects his religion and honour.",
    source: "Sahih al-Bukhari 52, from An-Nu'man ibn Bashir",
    confidence: "high",
  },
  {
    id: "hadith-026",
    pillar: "hadith",
    tier: "average",
    difficulty: 3,
    prompt: "According to a hadith, charity (sadaqah) does not —",
    options: ["Decrease wealth", "Increase fame", "Replace fasting", "Change one's destiny"],
    answerIndex: 0,
    explanation:
      "The hadith states: 'Charity does not decrease wealth.' It teaches that giving in charity brings blessing rather than loss.",
    source: "Sahih Muslim 2588, from Abu Hurayrah",
    confidence: "high",
  },
  {
    id: "hadith-027",
    pillar: "hadith",
    tier: "average",
    difficulty: 3,
    prompt: "Complete the hadith: 'If Allah wishes good for a person, He grants him — in the religion.'",
    options: ["Deep understanding (fiqh)", "Great wealth", "Many followers", "High status"],
    answerIndex: 0,
    explanation:
      "The Prophet said that when Allah wishes good for a person, He gives him understanding (fiqh) in the religion — religious knowledge and discernment.",
    source: "Sahih al-Bukhari 71, from Mu'awiyah",
    confidence: "high",
  },
  {
    id: "hadith-028",
    pillar: "hadith",
    tier: "average",
    difficulty: 3,
    prompt: "In a Qudsi hadith, Allah says every deed is rewarded for the person except —",
    options: [
      "Fasting, which is for Allah, Who rewards it directly",
      "Prayer, which is for Allah, Who rewards it directly",
      "Charity, which is for Allah, Who rewards it directly",
      "Hajj, which is for Allah, Who rewards it directly",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'All the deeds of Adam's children are for them, except fasting, for it is for Me, and I shall reward it.' Fasting is singled out in this Qudsi hadith.",
    source: "Sahih al-Bukhari 1904 (qudsi), from Abu Hurayrah",
    confidence: "high",
  },

  // ---- Intermediate expansion ----
  {
    id: "hadith-029",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 4,
    prompt: "In a hadith from An-Nawwas ibn Sam'an, how did the Prophet define 'birr' (righteousness)?",
    options: ["Good character", "Wealth given in charity", "Always speaking", "Never disputing"],
    answerIndex: 0,
    explanation:
      "When An-Nawwas asked about birr, the Prophet answered: 'Birr is good character.' The same hadith goes on to define sin as what wavers in the heart.",
    source: "Sahih Muslim 2553, from An-Nawwas ibn Sam'an",
    confidence: "high",
  },
  {
    id: "hadith-030",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 4,
    prompt: "According to a hadith, from the excellence of a person's Islam is that he —",
    options: [
      "Leaves what does not concern him",
      "Speaks in every gathering",
      "Wins every argument",
      "Competes in every deed",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'From the excellence of a person's Islam is that he leaves alone what does not concern him.' It teaches focus and avoidance of idle involvement.",
    source: "Jami' at-Tirmidhi 2318, from Abu Hurayrah",
    confidence: "high",
  },
  {
    id: "hadith-031",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 4,
    prompt: "Asked which verse is the greatest in the Quran, Ubayy ibn Ka'b answered —",
    options: [
      "Ayat al-Kursi (2:255)",
      "The last two verses of Al-Baqarah",
      "The opening verse of Al-Fatihah",
      "Surah Al-Ikhlas",
    ],
    answerIndex: 0,
    explanation:
      "When the Prophet asked Ubayy ibn Ka'b which verse was the greatest, he answered Ayat al-Kursi (2:255), and the Prophet affirmed this in delight.",
    source: "Sahih Muslim 810, from Ubayy ibn Ka'b",
    confidence: "high",
  },
  {
    id: "hadith-032",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 5,
    prompt: "According to a hadith, which two surahs will come 'as two clouds' on the Day of Judgement, interceding for their reciters?",
    options: [
      "Al-Baqarah and Al-Imran",
      "Al-Falaq and An-Nas",
      "Al-Kahf and Ya-Sin",
      "Al-Mulk and As-Sajdah",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet called Al-Baqarah and Al-Imran 'Az-Zahrawan' (the two luminous ones); on the Day of Judgement they will come as two clouds or two flocks of birds, pleading for those who recited them.",
    source: "Sahih Muslim 804, from Abu Umamah",
    confidence: "high",
  },
  {
    id: "hadith-033",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 2,
    prompt: "What did the Prophet say about those who overburden themselves in religion?",
    options: [
      "They will not be able to keep up",
      "Their reward is doubled",
      "They are raised in rank",
      "Their sins are forgiven",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Religion is very easy, and whoever overburdens himself in his religion will not be able to keep up. So be moderate, and give good tidings.'",
    source: "Sahih al-Bukhari 39, from Anas ibn Malik",
    confidence: "high",
  },
  {
    id: "hadith-034",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 2,
    prompt: "Complete the hadith: 'None of you [truly] believes until I am dearer to him than his family, his wealth, and...'",
    options: ["All mankind", "His own self", "His children", "His health"],
    answerIndex: 0,
    explanation:
      "The Prophet said a person's faith is not complete until the Prophet is dearer to them than anyone — family, wealth, and all mankind.",
    source: "Sahih al-Bukhari 15, from Anas ibn Malik",
    confidence: "high",
  },
  {
    id: "hadith-035",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 3,
    prompt: "According to a hadith, what does Allah look at when judging a person?",
    options: [
      "Their heart and their deeds",
      "Their wealth and their status",
      "Their lineage and their beauty",
      "Their speech and their reputation",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Allah does not look at your appearance and wealth, but He looks at your hearts and your deeds.'",
    source: "Sahih Muslim 2564, from Abu Huraira",
    confidence: "high",
  },
  {
    id: "hadith-036",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 3,
    prompt: "About which person did the Prophet say 'By Allah, he does not believe' three times?",
    options: [
      "One whose neighbour is not safe from his harm",
      "One who misses the Friday prayer",
      "One who does not give charity",
      "One who backbites about others",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet repeated three times that one whose neighbour does not feel safe from his harm is not a believer — a strong warning about mistreating neighbours.",
    source: "Sahih al-Bukhari 6016, from Abu Huraira",
    confidence: "high",
  },
  {
    id: "hadith-037",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 3,
    prompt: "In the hadith on companionship, to what did the Prophet compare a good companion?",
    options: [
      "A carrier of musk (perfume)",
      "A fruit tree",
      "A flowing river",
      "A bright lamp",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet compared a good companion to a carrier of musk — his company brings benefit even when he gives nothing — and a bad companion to a blacksmith's bellows, which scorch or fill you with smoke.",
    source: "Sahih al-Bukhari 2101, from Abu Musa al-Ash'ari",
    confidence: "high",
  },
  {
    id: "hadith-038",
    pillar: "hadith",
    tier: "average",
    difficulty: 4,
    prompt: "According to a hadith, who will not enter Paradise?",
    options: [
      "One who has an atom's weight of pride (arrogance) in their heart",
      "One who has never fasted",
      "One who speaks harshly",
      "One who is wealthy",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'No one who has an atom's weight of arrogance in his heart will enter Paradise.' Pride is refusing the truth and belittling people.",
    source: "Sahih Muslim 91, from Abdullah ibn Mas'ud",
    confidence: "high",
  },
  {
    id: "hadith-039",
    pillar: "hadith",
    tier: "average",
    difficulty: 4,
    prompt: "What did the Prophet say oppression (dhulm) will be on the Day of Judgement?",
    options: [
      "Darkness upon darkness",
      "A heavy burden",
      "A blazing fire",
      "A sealed record",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet warned: 'Beware of oppression, for oppression will be layers of darkness on the Day of Judgement.'",
    source: "Sahih Muslim 2578, from Abdullah ibn Umar",
    confidence: "high",
  },
  {
    id: "hadith-040",
    pillar: "hadith",
    tier: "average",
    difficulty: 4,
    prompt: "To what did the Prophet compare Allah's joy when a servant repents?",
    options: [
      "A man who finds his lost camel in the desert after searching for it",
      "A farmer who harvests his crop",
      "A traveller who reaches home safely",
      "A father who sees his newborn child",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet described a man who loses his camel in the desert — and, despairing, finds it again — as rejoicing even more than that is Allah's joy at a servant's repentance.",
    source: "Sahih Muslim 2749, from Nu'man ibn Bashir",
    confidence: "high",
  },
  {
    id: "hadith-041",
    pillar: "hadith",
    tier: "average",
    difficulty: 4,
    prompt: "What did the Prophet say is the heaviest thing on the believer's scales on the Day of Judgement?",
    options: [
      "Good character",
      "Much wealth given in charity",
      "Long nights of prayer",
      "The Hajj pilgrimage",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Nothing will be heavier on the believer's scale on the Day of Judgement than good character.'",
    source: "Sunan Abi Dawud 4799, from Abu Huraira",
    confidence: "high",
  },
  {
    id: "hadith-042",
    pillar: "hadith",
    tier: "average",
    difficulty: 4,
    prompt: "In the hadith 'Fear Allah wherever you are', what is the believer told to do after a bad deed?",
    options: [
      "Follow it with a good deed that will erase it",
      "Fast for three days",
      "Seek a scholar's verdict",
      "Confess it publicly",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Fear Allah wherever you are, follow a bad deed with a good deed which will erase it, and behave with good character toward people.'",
    source: "Jami' at-Tirmidhi 1987, from Abu Dharr",
    confidence: "high",
  },
  {
    id: "hadith-043",
    pillar: "hadith",
    tier: "average",
    difficulty: 4,
    prompt: "How did the Prophet describe the believer in relation to his fellow believer?",
    options: [
      "The mirror of his fellow believer",
      "A shield against evil",
      "A lamp lighting the path",
      "A wall that protects him",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'The believer is the mirror of his fellow believer' — he sees his brother's faults and shows him, and guards his brother when he is absent.",
    source: "Sunan Abi Dawud 4918, from Abu Huraira",
    confidence: "high",
  },
  {
    id: "hadith-044",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 4,
    prompt: "Which two phrases did the Prophet say are 'light on the tongue, heavy in the balance'?",
    options: [
      "'Subhan Allahi wa bi-hamdihi, Subhan Allahi-l-'Adhim'",
      "'La ilaha illa Allah, Muhammadur Rasul Allah'",
      "'Alhamdulillah, Allahu Akbar'",
      "'Astaghfirullah, La hawla wa la quwwata'",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said these two phrases — 'Glory and praise to Allah; glory to Allah the Magnificent' — are light on the tongue but weigh heavy in the balance on the Day of Judgement.",
    source: "Sahih al-Bukhari 6682, from Abu Huraira",
    confidence: "high",
  },
  {
    id: "hadith-045",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 4,
    prompt: "Complete the hadith: 'Convey from me even if it is...'",
    options: ["One verse", "One word", "One letter", "One surah"],
    answerIndex: 0,
    explanation:
      "The Prophet instructed: 'Convey from me even if it is one verse', urging believers to transmit knowledge however little they have of it.",
    source: "Sahih al-Bukhari 3461, from Abdullah ibn Amr",
    confidence: "high",
  },
  {
    id: "hadith-046",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 5,
    prompt: "What does the hadith 'The believer is not stung from the same hole twice' teach?",
    options: [
      "The believer learns from harm and does not repeat the same mistake",
      "A believer should always be cautious around snakes",
      "Sins are forgiven after repentance",
      "The believer is protected from all harm",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet's proverb teaches wisdom and prudence: a believer is not deceived twice the same way — he learns from past experience and does not repeat his errors.",
    source: "Sahih al-Bukhari 6133, from Abu Huraira",
    confidence: "high",
  },
  {
    id: "hadith-047",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 5,
    prompt: "According to a hadith, which two eyes will not be touched by the Fire?",
    options: [
      "An eye that wept from fear of Allah, and an eye that stayed awake guarding in Allah's cause",
      "An eye that weeps over a lost loved one, and an eye that reads the Quran",
      "An eye that avoids looking at the forbidden, and an eye that looks upon the Kaaba",
      "An eye that sheds tears in charity, and an eye that watches for dawn",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said two eyes will never be touched by the Fire: one that wept from fear of Allah, and one that spent the night standing guard in the path of Allah.",
    source: "Jami' at-Tirmidhi 1639",
    confidence: "high",
  },
  {
    id: "hadith-048",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 5,
    prompt: "How did the Prophet describe the pain a martyr feels when he is killed?",
    options: [
      "No more than the pain of a pinch",
      "Like a sword cutting flesh",
      "Like a fire burning the body",
      "The martyr feels no pain at all",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said the martyr feels the pain of death no more than one of you feels a pinch — a comfort about the ease of death for those who die in Allah's cause.",
    source: "Jami' at-Tirmidhi 1668",
    confidence: "high",
  },
  {
    id: "hadith-049",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 5,
    prompt: "According to a hadith, what will make believers love one another and thereby enter Paradise?",
    options: [
      "Spreading salam (the greeting of peace) among themselves",
      "Gathering together in congregation",
      "Giving charity to the poor",
      "Visiting one another frequently",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'You will not enter Paradise until you believe, and you will not believe until you love one another. Shall I tell you what will make you love one another? Spread salam among you.'",
    source: "Jami' at-Tirmidhi 2485, from Abu Huraira",
    confidence: "high",
  },
  {
    id: "hadith-050",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 3,
    prompt: "In the hadith, what did Allah write in His Book before creating the creation?",
    options: [
      "My mercy overcomes My wrath",
      "My punishment is severe",
      "My reward is great for the believers",
      "My mercy is only for the merciful",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'When Allah created the creation, He put down in His Book: Verily, My mercy predominates My wrath.'",
    source: "Sahih Muslim 2751, from Abu Huraira",
    confidence: "high",
  },
  {
    id: "hadith-051",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 2,
    prompt: "Complete the hadith: 'Religion (the deen) is ...'",
    options: [
      "sincerity (naseehah)",
      "hardship (mushaqqah)",
      "abstinence (zuhd)",
      "knowledge ('ilm)",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Religion is sincerity (naseehah).' He repeated it three times — sincerity to Allah, His Book, His Messenger, the Muslim leaders, and all the people.",
    source: "Sahih Muslim 55, from Tamim ad-Dari",
    confidence: "high",
  },
  {
    id: "hadith-052",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 2,
    prompt: "According to the hadith, what act is counted as charity (sadaqah)?",
    options: [
      "Your smile in the face of your brother",
      "Fasting on Mondays",
      "Reciting the Quran aloud",
      "Wearing clean clothes",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Your smile in the face of your brother is charity, and commanding good and forbidding evil is charity' — every good deed toward creation is a form of sadaqah.",
    source: "Jami' at-Tirmidhi 1956, from Abu Dharr",
    confidence: "high",
  },
  {
    id: "hadith-053",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 3,
    prompt: "What did the Prophet say a Muslim should not do to his fellow Muslim — in the hadith 'A Muslim is the brother of a Muslim'?",
    options: [
      "Oppress him, despise him, or forsake him",
      "Compete with him in trade",
      "Borrow from him without repaying",
      "Keep his counsel a secret",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'A Muslim is the brother of a Muslim. He does not oppress him, does not forsake him, and does not despise him. Taqwa (God-consciousness) is here' — pointing to his heart.",
    source: "Sahih Muslim 2580, from Abu Huraira",
    confidence: "high",
  },
  {
    id: "hadith-054",
    pillar: "hadith",
    tier: "average",
    difficulty: 4,
    prompt: "According to the hadith, what does envy (hasad) do to good deeds?",
    options: [
      "It devours them as fire devours wood",
      "It doubles them like charity",
      "It protects them from sin",
      "It stores them for the afterlife",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Beware of envy, for envy consumes good deeds just as fire consumes wood.'",
    source: "Sunan Abi Dawud 4903, from Abu Huraira",
    confidence: "high",
  },
  {
    id: "hadith-055",
    pillar: "hadith",
    tier: "average",
    difficulty: 3,
    prompt: "When a man asked the Prophet for advice and repeated his request, what did the Prophet say three times?",
    options: [
      "Do not become angry",
      "Pray the night prayer",
      "Speak good or remain silent",
      "Guard your tongue",
    ],
    answerIndex: 0,
    explanation:
      "A man asked the Prophet for advice; the Prophet said 'Do not become angry' and repeated it three times.",
    source: "Sahih al-Bukhari 6116, from Abu Huraira",
    confidence: "high",
  },
  {
    id: "hadith-056",
    pillar: "hadith",
    tier: "average",
    difficulty: 4,
    prompt: "How many people does Allah shade with His shade on the Day when there is no shade but His?",
    options: [
      "Seven",
      "Ten",
      "Five",
      "Twelve",
    ],
    answerIndex: 0,
    explanation:
      "Seven are shaded: a just ruler, a youth who grows up worshipping Allah, one whose heart is attached to the mosque, two who love each other for Allah, a man who rejects the invitation of a beautiful high-status woman, one who gives charity in secret, and one who remembers Allah alone with tearful eyes.",
    source: "Sahih Muslim 1031, from Abu Huraira",
    confidence: "high",
  },
  {
    id: "hadith-057",
    pillar: "hadith",
    tier: "average",
    difficulty: 4,
    prompt: "In the hadith, who is like the one who strives in the path of Allah?",
    options: [
      "One who looks after a widow or an orphan",
      "One who fasts every other day",
      "One who memorises the Quran",
      "One who prays in the first row",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'The one who looks after a widow or an orphan is like the one who strives in the path of Allah' — or like one who stands for night prayer and fasts without pause.",
    source: "Sahih Muslim 2982, from Abu Huraira",
    confidence: "high",
  },
  {
    id: "hadith-058",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 5,
    prompt: "In the hadith, what order is given for changing an evil (munkar)?",
    options: [
      "With the hand; if unable, with the tongue; if unable, with the heart",
      "With the tongue; if unable, with the hand; if unable, with prayer",
      "With prayer; if unable, with fasting; if unable, with silence",
      "With the heart only; never with the hand or tongue",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Whoever among you sees an evil, let him change it with his hand; if unable, then with his tongue; if unable, then with his heart — and that is the weakest of faith.'",
    source: "Sahih Muslim 49, from Abu Sa'id al-Khudri",
    confidence: "high",
  },
  {
    id: "hadith-059",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 4,
    prompt: "In the Farewell Sermon, what did the Prophet declare sacred among the believers?",
    options: [
      "Their lives, their property, and their honour",
      "Their prayers, their fasting, and their charity",
      "Their scholars, their leaders, and their elders",
      "Their names, their lineage, and their trade",
    ],
    answerIndex: 0,
    explanation:
      "In the Farewell Sermon the Prophet declared: 'Your lives, your property, and your honour are sacred to one another' — as sacred as this day, this month, and this city.",
    source: "Sahih Muslim 1679",
    confidence: "high",
  },
  {
    id: "hadith-060",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 4,
    prompt: "To what did the Prophet liken the believer among the trees?",
    options: [
      "The date-palm, whose leaves never fall",
      "The olive tree, rich in oil",
      "The fig tree, soft and sweet",
      "The cypress, tall and straight",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet told Abdullah ibn Umar that among the trees there is one like a believer whose leaves never fall — the date-palm, which is always fruitful and benefits others.",
    source: "Sahih Muslim 2811, from Abdullah ibn Umar",
    confidence: "high",
  },
  {
    id: "hadith-061",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 5,
    prompt: "When a person dies, his deeds come to an end except for three. Which of these is one of them?",
    options: [
      "A righteous child who prays for him",
      "A large estate left behind",
      "A famous reputation",
      "A mosque built in his name",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'When a person dies, his deeds come to an end except for three: ongoing charity (sadaqah jariyah), knowledge from which benefit is derived, and a righteous child who prays for him.'",
    source: "Sahih Muslim 1631, from Abu Huraira",
    confidence: "high",
  },
  {
    id: "hadith-062",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 3,
    prompt: "What did the Prophet say about Allah and mercy toward His creation?",
    options: [
      "Whoever does not show mercy to people, Allah will not show mercy to him",
      "Mercy is only for the righteous few",
      "Mercy is earned through wealth",
      "Allah's mercy is reserved for the Day of Judgement",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Whoever does not show mercy to people, Allah will not show mercy to him.'",
    source: "Sahih Muslim 2319, from Jarir ibn Abdullah",
    confidence: "high",
  },
  {
    id: "hadith-063",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 3,
    prompt: "In the hadith, whoever possesses three qualities will find the sweetness of faith. Which is one of them?",
    options: [
      "That Allah and His Messenger are dearer to him than all else",
      "That he owns a large garden",
      "That he memorises the entire Quran",
      "That he travels for knowledge",
    ],
    answerIndex: 0,
    explanation:
      "Three things give the taste of faith: that Allah and His Messenger are dearer to him than all else, that he loves a person only for Allah's sake, and that he hates returning to disbelief as he would hate being thrown into the fire.",
    source: "Sahih Muslim 43, from Anas ibn Malik",
    confidence: "high",
  },
  {
    id: "hadith-064",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 5,
    prompt: "According to the hadith, what is the fate of the one who is silent?",
    options: [
      "He is saved",
      "He is rewarded only if he speaks",
      "He is forgotten",
      "He is considered proud",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Whoever believes in Allah and the Last Day, let him speak good or remain silent' — and 'Whoever is silent is saved.'",
    source: "Jami' at-Tirmidhi 2501, from Abu Huraira",
    confidence: "high",
  },
  {
    id: "hadith-065",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 3,
    prompt: "In the hadith, envy (hasad) is permitted in only two cases. Which is one of them?",
    options: [
      "A man given wealth by Allah who spends it righteously",
      "A man given fame who enjoys its benefits",
      "A man given beauty who is admired by people",
      "A man given strength who dominates others",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'There is no envy except in two: a man whom Allah has given wealth and he spends it in the right way, and a man whom Allah has given wisdom and he judges by it and teaches it.'",
    source: "Sahih Muslim 816, from Abdullah ibn Mas'ud",
    confidence: "high",
  },
  {
    id: "hadith-066",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 3,
    prompt: "How did the Prophet describe suspicion (zann)?",
    options: [
      "The most false of speech",
      "A sign of wisdom",
      "A praiseworthy caution",
      "A shield against deception",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Beware of suspicion, for suspicion is the most false of speech. Do not spy, do not envy one another, do not hate one another, and be brothers.'",
    source: "Sahih Muslim 2563, from Abu Huraira",
    confidence: "high",
  },
  {
    id: "hadith-067",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 2,
    prompt: "Which recommendation did the angel Jibril keep repeating to the Prophet until he thought the neighbour would inherit?",
    options: [
      "Kindness to the neighbour",
      "Frequent fasting",
      "Night prayer",
      "Zakat on wealth",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Jibril kept advising me about the neighbour until I thought he would make the neighbour an heir.'",
    source: "Sahih al-Bukhari 6015, from Aisha",
    confidence: "high",
  },
  {
    id: "hadith-068",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 2,
    prompt: "In the hadith, whoever believes in Allah and the Last Day should do what?",
    options: [
      "Honour his guest",
      "Increase his wealth",
      "Speak constantly",
      "Travel extensively",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Whoever believes in Allah and the Last Day, let him honour his guest' — along with speaking good or remaining silent.",
    source: "Sahih al-Bukhari 6019, from Abu Huraira",
    confidence: "high",
  },
  {
    id: "hadith-069",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 2,
    prompt: "How did the Prophet define those who are not 'of us' in the hadith about mercy and respect?",
    options: [
      "Those who do not show mercy to our young or respect our elders",
      "Those who do not attend the Friday prayer",
      "Those who do not grow beards",
      "Those who do not memorise the Quran",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'He is not of us who does not show mercy to our young ones and does not respect our elders.'",
    source: "Jami' at-Tirmidhi 1920, from Abdullah ibn Amr",
    confidence: "high",
  },
  {
    id: "hadith-070",
    pillar: "hadith",
    tier: "average",
    difficulty: 4,
    prompt: "In the hadith to Abdullah ibn Amr about continuous fasting, what rights did the Prophet say the body and family have?",
    options: [
      "Your body has a right over you, and your family has a right over you",
      "Your desires must always come before worship",
      "Your body has no rights once you begin to pray",
      "Only the soul matters, not the body",
    ],
    answerIndex: 0,
    explanation:
      "When Abdullah ibn Amr resolved to fast always and pray all night, the Prophet corrected him: 'Your body has a right over you, your eyes have a right over you, and your wife has a right over you' — teaching balance in worship.",
    source: "Sahih Muslim 1159, from Abdullah ibn Amr",
    confidence: "high",
  },
  {
    id: "hadith-071",
    pillar: "hadith",
    tier: "average",
    difficulty: 3,
    prompt: "When Abdullah ibn Mas'ud asked which deed is most beloved to Allah, what was the Prophet's answer?",
    options: [
      "Prayer at its proper time",
      "Fasting every day",
      "Performing Hajj yearly",
      "Reciting the Quran aloud",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet replied: 'Prayer at its proper time.' Asked then what, he said 'Kindness to parents,' then 'Jihad in the path of Allah.'",
    source: "Sahih Muslim 85, from Abdullah ibn Mas'ud",
    confidence: "high",
  },
  {
    id: "hadith-072",
    pillar: "hadith",
    tier: "average",
    difficulty: 4,
    prompt: "According to the hadith, whom does a person follow?",
    options: [
      "The religion of his close friend",
      "The customs of his city",
      "The example of his ancestors",
      "The habits of his employer",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'A man follows the religion of his close friend, so let each of you look to whom he takes as a friend.'",
    source: "Sunan Abi Dawud 4833, from Abu Huraira",
    confidence: "high",
  },
  {
    id: "hadith-073",
    pillar: "hadith",
    tier: "average",
    difficulty: 4,
    prompt: "How did the Prophet define true wealth?",
    options: [
      "Wealth is not in many possessions but in contentment of the soul",
      "Wealth is measured by gold and silver",
      "Wealth is the abundance of land and cattle",
      "Wealth is the size of one's family",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Wealth is not in having many possessions; rather, true wealth is the contentment of the soul.'",
    source: "Sahih Muslim 1051, from Abu Huraira",
    confidence: "high",
  },
  {
    id: "hadith-074",
    pillar: "hadith",
    tier: "average",
    difficulty: 4,
    prompt: "Which four words did the Prophet say are the most beloved speech to Allah?",
    options: [
      "SubhanAllah, Alhamdulillah, La ilaha illa Allah, Allahu Akbar",
      "La hawla, wa la quwwata illa billah",
      "A'udhu billahi min ash-shaytan ir-rajim",
      "Bismillah ir-Rahman ir-Rahim",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said the most beloved speech to Allah are four: 'SubhanAllah' (Glory be to Allah), 'Alhamdulillah' (Praise be to Allah), 'La ilaha illa Allah' (There is no god but Allah), and 'Allahu Akbar' (Allah is the Greatest) — whichever you begin with is fine.",
    source: "Sahih Muslim 2137, from Samura ibn Jundub",
    confidence: "high",
  },
  {
    id: "hadith-075",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 5,
    prompt: "According to the hadith, what happens to the one who loves to meet Allah?",
    options: [
      "Allah loves to meet him",
      "He will never taste death",
      "He will be spared the Day of Judgement",
      "His sins are forgiven without asking",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Whoever loves to meet Allah, Allah loves to meet him; and whoever hates to meet Allah, Allah hates to meet him' — loving to meet Allah means loving what comes after this world.",
    source: "Sahih Muslim 2683, from Aisha",
    confidence: "high",
  },
  {
    id: "hadith-076",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 5,
    prompt: "What did the Prophet say about every son of Adam and those who err?",
    options: [
      "Every son of Adam errs, and the best of those who err are the repentant",
      "Only the ignorant err, and the learned are perfect",
      "Errors are unforgivable except after death",
      "The errant should never be forgiven",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Every son of Adam errs, and the best of those who err are the repentant' (tawwabun) — repeatedly returning to Allah in repentance.",
    source: "Jami' at-Tirmidhi 2499, from Anas ibn Malik",
    confidence: "high",
  },
  {
    id: "hadith-077",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 5,
    prompt: "What did the Prophet prohibit among Muslims alongside cutting ties?",
    options: [
      "Mutual jealousy, hatred, and turning away from one another",
      "Fair trading and honest dealing",
      "Giving charity in secret",
      "Praying in congregation",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Do not cut off ties, do not turn your backs on one another, do not hate one another, and do not envy one another. Be servants of Allah, brothers.'",
    source: "Sahih Muslim 2559, from Anas ibn Malik",
    confidence: "high",
  },
  {
    id: "hadith-078",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 4,
    prompt: "According to the hadith, what is the connection between thanking people and thanking Allah?",
    options: [
      "Whoever does not thank people does not thank Allah",
      "Thanking people is more important than thanking Allah",
      "Thanking Allah replaces the need to thank people",
      "People should be thanked only in public",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Whoever does not thank people does not thank Allah' — gratitude to Allah is shown through gratitude to His creation.",
    source: "Sunan Abi Dawud 4811, from Abu Huraira",
    confidence: "high",
  },
  {
    id: "hadith-079",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 4,
    prompt: "Which prayer did the Prophet call the best after the obligatory prayers?",
    options: [
      "The night prayer (tahajjud)",
      "The two rakahs before Fajr",
      "The Eid prayer",
      "The Friday prayer",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'The best prayer after the obligatory prayers is the night prayer (qiyam al-layl), and the best fasting after Ramadan is in the month of Muharram.'",
    source: "Sahih Muslim 1163, from Abu Huraira",
    confidence: "high",
  },
  {
    id: "hadith-080",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 4,
    prompt: "What did the Prophet say fasting on Ashura (the 10th of Muharram) expiates?",
    options: [
      "The sins of the previous year",
      "All sins for a lifetime",
      "Only minor sins of that month",
      "Nothing — it is merely a custom",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said fasting on the day of Ashura expiates the sins of the previous year, and fasting on Arafah expiates the sins of the previous and following years.",
    source: "Sahih Muslim 1162, from Abu Qatada",
    confidence: "high",
  },
  {
    id: "hadith-081",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 3,
    prompt: "In the hadith about giving, which hand did the Prophet say is better?",
    options: [
      "The upper hand (the one that gives)",
      "The lower hand (the one that receives)",
      "The right hand over the left",
      "Both hands are equal",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'The upper hand (that gives) is better than the lower hand (that receives). Begin with those you support' — encouraging giving over taking.",
    source: "Sahih Muslim 1033, from Hakim ibn Hizam",
    confidence: "high",
  },
  {
    id: "hadith-082",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 3,
    prompt: "In the hadith, when a Muslim makes a supplication with no sin or cutting of ties in it, how does Allah respond?",
    options: [
      "He grants it, or reserves it, or turns away an equal evil from him",
      "He answers only when the du'a is made in the mosque",
      "He answers only if repeated seventy times",
      "He answers only at night",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'There is no Muslim who calls upon Allah with a supplication free of sin and cutting ties except that Allah gives him one of three things: He grants his request, or reserves it for the Hereafter, or turns away an equal evil from him.'",
    source: "Sahih Muslim 2735, from Abu Sa'id al-Khudri",
    confidence: "high",
  },
  {
    id: "hadith-083",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 2,
    prompt: "What did the Prophet say modesty (haya) brings?",
    options: [
      "Nothing but good",
      "Wealth and status",
      "Weakness in dealings",
      "Fear of people",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Modesty (haya) does not bring anything but good' — a virtue that prevents evil and beautifies the believer.",
    source: "Sahih Muslim 37, from Imran ibn Husayn",
    confidence: "high",
  },
  {
    id: "hadith-084",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 2,
    prompt: "In the hadith, what is counted as charity when a Muslim plants a tree?",
    options: [
      "Whatever is eaten from it — by birds, animals, or people",
      "Only the fruit he sells",
      "Only the shade it gives him",
      "Nothing — planting is not charity",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'No Muslim plants a tree or sows a crop and then a bird, person, or animal eats from it except that it is charity for him.'",
    source: "Sahih Muslim 1552, from Anas ibn Malik",
    confidence: "high",
  },
  {
    id: "hadith-085",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 2,
    prompt: "Which places did the Prophet say are the most beloved to Allah, and the most hated?",
    options: [
      "The mosques are most beloved; the markets are most hated",
      "The homes are most beloved; the roads are most hated",
      "The gardens are most beloved; the deserts are most hated",
      "The mountains are most beloved; the seas are most hated",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'The most beloved of places to Allah are the mosques, and the most hated of places to Allah are the markets.'",
    source: "Sahih Muslim 671, from Abu Huraira",
    confidence: "high",
  },
  {
    id: "hadith-086",
    pillar: "hadith",
    tier: "average",
    difficulty: 4,
    prompt: "When did the Prophet say charity is best given?",
    options: [
      "While you are healthy and in need, hoping to grow rich but fearing poverty",
      "Only after accumulating great wealth",
      "Only at the time of death",
      "Only in the last ten nights of Ramadan",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'The best charity is that given while you are healthy and in need, hoping to grow rich but fearing poverty. Do not delay until your soul reaches your throat.'",
    source: "Sahih Muslim 1032, from Abu Huraira",
    confidence: "high",
  },
  {
    id: "hadith-087",
    pillar: "hadith",
    tier: "average",
    difficulty: 4,
    prompt: "In the hadith, what does a Muslim receive for visiting a sick Muslim brother?",
    options: [
      "He remains in a garden of Paradise for the duration of the visit",
      "He is exempt from fasting that day",
      "He receives double reward for his own prayers",
      "He is guaranteed entry to Paradise",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'When a man visits his sick Muslim brother, he remains in a garden (khurfa) of Paradise until he returns.'",
    source: "Sahih Muslim 2568, from Thawban",
    confidence: "high",
  },
  {
    id: "hadith-088",
    pillar: "hadith",
    tier: "average",
    difficulty: 4,
    prompt: "What did the Prophet promise the one who builds a mosque for Allah?",
    options: [
      "Allah will build for him a house in Paradise",
      "Allah will forgive all his past sins",
      "Allah will increase his wealth in this world",
      "Allah will appoint him a leader of his people",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Whoever builds a mosque for Allah, Allah will build for him the like of it in Paradise.'",
    source: "Sahih Muslim 533, from Uthman ibn Affan",
    confidence: "high",
  },
  {
    id: "hadith-089",
    pillar: "hadith",
    tier: "average",
    difficulty: 4,
    prompt: "Which five rights does a Muslim have over his fellow Muslim?",
    options: [
      "Returning the greeting, visiting the sick, following funerals, accepting invitations, and answering sneezes",
      "Sharing wealth, lending without interest, giving gifts, praising, and defending",
      "Praying with him, fasting with him, giving zakat with him, and two more",
      "Inviting to meals, lending money, visiting, advising, and gifting",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'The rights of a Muslim over a Muslim are five: returning the greeting of salam, visiting the sick, following funeral processions, accepting invitations, and responding to the one who sneezes (saying yarhamukallah).'",
    source: "Sahih Muslim 2162, from Abu Huraira",
    confidence: "high",
  },
  {
    id: "hadith-090",
    pillar: "hadith",
    tier: "average",
    difficulty: 4,
    prompt: "What did the Prophet say about the one who severs ties of kinship?",
    options: [
      "He will not enter Paradise",
      "He will be forgiven after forty days",
      "His charity is not accepted",
      "He must fast to atone",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'The one who severs the ties of kinship will not enter Paradise.'",
    source: "Sahih Muslim 2556, from Jubayr ibn Mut'im",
    confidence: "high",
  },
  {
    id: "hadith-091",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 5,
    prompt: "Which supplication did the Prophet call the best?",
    options: [
      "The supplication on the Day of Arafah",
      "The supplication during prostration",
      "The supplication after the night prayer",
      "The supplication in the last hour of Friday",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'The best of supplications is the supplication on the Day of Arafah, and the best of what I and the prophets before me said is: La ilaha illa Allah wahdahu la sharika lah.'",
    source: "Jami' at-Tirmidhi 3585, from Amr ibn Shu'ayb",
    confidence: "high",
  },
  {
    id: "hadith-092",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 4,
    prompt: "What did the Prophet promise the one who preserves (memorises and lives by) the names of Allah?",
    options: [
      "He will enter Paradise",
      "He will never be poor",
      "He will have his du'as answered instantly",
      "He will be protected from magic",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Allah has ninety-nine names — one hundred minus one. Whoever preserves them (or enumerates them) will enter Paradise.'",
    source: "Sahih Muslim 2677, from Abu Huraira",
    confidence: "high",
  },
  {
    id: "hadith-093",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 4,
    prompt: "When was the Prophet most generous, according to Ibn Abbas?",
    options: [
      "In Ramadan, when Jibril met him and reviewed the Quran with him",
      "On Fridays before the sermon",
      "In the first ten days of Dhul-Hijjah",
      "On the day of Eid",
    ],
    answerIndex: 0,
    explanation:
      "Ibn Abbas said the Prophet was the most generous of people, and he was most generous in Ramadan when Jibril came to meet him each night to review the Quran — he was more generous than the free wind.",
    source: "Sahih al-Bukhari 6, from Ibn Abbas",
    confidence: "high",
  },
  {
    id: "hadith-094",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 5,
    prompt: "Whose striving (jihad) did the Prophet say is truly in the path of Allah?",
    options: [
      "One who fights so that the word of Allah is supreme",
      "One who fights for fame and spoils",
      "One who fights to defend his tribe only",
      "One who fights out of anger",
    ],
    answerIndex: 0,
    explanation:
      "Asked which warrior fights truly in the path of Allah, the Prophet said: 'One who fights so that the word of Allah is the highest.'",
    source: "Sahih Muslim 1904, from Abdullah ibn Mas'ud",
    confidence: "high",
  },
  {
    id: "hadith-095",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 5,
    prompt: "In the hadith, what reward does the one who guides others to good receive?",
    options: [
      "A reward like that of those who act upon it, without their reward being reduced",
      "Nothing — only the doer is rewarded",
      "Half the reward of the doer",
      "A reward only in this world",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Whoever guides to a good deed gets a reward like that of the one who does it, without the doer's reward being reduced in any way.'",
    source: "Sahih Muslim 1893, from Abu Dharr",
    confidence: "high",
  },

  // ---- Final expansion: hadith-096..110 ----
  {
    id: "hadith-096",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 2,
    prompt: "In a hadith from Aisha, what does Allah love above all?",
    options: [
      "Gentleness in all matters",
      "Harshness in all matters",
      "Loudness in worship",
      "Haste in all matters",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Allah is gentle and loves gentleness in all things.' Gentleness is the way that brings good, as the Prophet taught throughout his life.",
    source: "Sahih Muslim 2593, from Aisha",
    confidence: "high",
  },
  {
    id: "hadith-097",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 2,
    prompt: "In a hadith from Aisha, who is the best of you?",
    options: [
      "The one who is best to his family",
      "The one who owns the most property",
      "The one who travels the most",
      "The one who speaks the most",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'The best of you is the best to his family, and I am the best of you to my family.' Kindness begins at home.",
    source: "Jami' at-Tirmidhi 3895, from Aisha",
    confidence: "high",
  },
  {
    id: "hadith-098",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 2,
    prompt: "Which of these did the Prophet list among the seven destructive sins?",
    options: [
      "Consuming the orphan's wealth",
      "Eating while walking",
      "Sleeping past Fajr",
      "Traveling without provision",
    ],
    answerIndex: 0,
    explanation:
      "The seven destructive sins include: ascribing partners to Allah, magic, killing a soul, consuming riba, consuming the orphan's wealth, fleeing from battle, and slandering chaste believing women.",
    source: "Sahih Muslim 89, from Abu Hurayrah",
    confidence: "high",
  },
  {
    id: "hadith-099",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 2,
    prompt: "In a hadith from Abu Hurayrah, what is the reward for saying 'SubhanAllahi wa bihamdihi' 100 times a day?",
    options: [
      "Sins are forgiven even if they were like the foam of the sea",
      "A house is built in Paradise for each repetition",
      "A year of fasting is counted",
      "All prayers are accepted for that day",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Whoever says SubhanAllahi wa bihamdihi 100 times in a day, his sins are forgiven even if they were like the foam of the sea.'",
    source: "Sahih Muslim 2691, from Abu Hurayrah",
    confidence: "high",
  },
  {
    id: "hadith-100",
    pillar: "hadith",
    tier: "newbie",
    difficulty: 2,
    prompt: "In the hadith on the virtue of treating daughters well, what will daughters be for the father who raises them well?",
    options: [
      "A shield for him from the Fire",
      "A source of wealth in this world",
      "A crown to show off with",
      "A punishment for him in the Hereafter",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet taught that whoever treats his daughters well, they will be a shield protecting him from the Fire. Caring for and educating daughters brings immense reward.",
    source: "Sahih Muslim 2629, chapter on the virtue of treating daughters well",
    confidence: "high",
  },
  {
    id: "hadith-101",
    pillar: "hadith",
    tier: "average",
    difficulty: 3,
    prompt: "In a hadith on purification, what does Allah not accept without taharah (purification)?",
    options: [
      "Prayer (salah)",
      "Charity (sadaqah)",
      "Fasting (sawm)",
      "Remembrance (dhikr)",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Allah does not accept prayer without purification.' Wudu or ghusl is a prerequisite for the validity of salah.",
    source: "Sahih Muslim 224, from Abu Hurayrah",
    confidence: "high",
  },
  {
    id: "hadith-102",
    pillar: "hadith",
    tier: "average",
    difficulty: 3,
    prompt: "In a hadith from Jundub ibn Abdullah, what is the person who prays Fajr under?",
    options: [
      "The protection of Allah",
      "The shade of a cloud",
      "The custody of his parents",
      "The watch of the angels only",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Whoever prays the Fajr prayer is under the protection of Allah.' Praying Fajr places the believer under Allah's safeguard.",
    source: "Sahih Muslim 657, from Jundub ibn Abdullah",
    confidence: "high",
  },
  {
    id: "hadith-103",
    pillar: "hadith",
    tier: "average",
    difficulty: 3,
    prompt: "In a hadith from Abu Hurayrah, what is this world for the believer?",
    options: [
      "A prison",
      "A garden",
      "A playground",
      "A mirror",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'The world is a prison for the believer and a paradise for the disbeliever.' The believer's true home is the Hereafter, so worldly hardship is temporary.",
    source: "Sahih Muslim 2956, from Abu Hurayrah",
    confidence: "high",
  },
  {
    id: "hadith-104",
    pillar: "hadith",
    tier: "average",
    difficulty: 3,
    prompt: "In a hadith from Aisha, what happens when hardship or a thorn prick befalls a believer?",
    options: [
      "Their sins are expiated",
      "Their rank is lowered",
      "Their reward is cancelled",
      "Nothing changes",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said that no fatigue, illness, sorrow, or even a thorn prick befalls a believer without Allah expiating some of their sins because of it.",
    source: "Sahih Muslim 2573, from Aisha",
    confidence: "high",
  },
  {
    id: "hadith-105",
    pillar: "hadith",
    tier: "average",
    difficulty: 3,
    prompt: "In a hadith from Abu Hurayrah, what did the Prophet say about the fasting person who does not give up false speech and false deeds?",
    options: [
      "Allah has no need of him giving up his food and drink",
      "His fast becomes doubly rewarded",
      "His fast is accepted without question",
      "He must repeat the day after Ramadan",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Whoever does not give up false speech and false deeds, Allah has no need of him giving up his food and drink.' Fasting is meant to purify conduct, not just abstain from food.",
    source: "Sahih al-Bukhari 6057, from Abu Hurayrah",
    confidence: "high",
  },
  {
    id: "hadith-106",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 5,
    prompt: "In a hadith from Abdullah ibn Amr, where will those who are just be seated on the Day of Resurrection?",
    options: [
      "On pulpits of light, near Allah, on the right of the Most Merciful",
      "On thrones of gold among the rulers of this world",
      "At the gates of Paradise, waiting for entry",
      "Under the shade of the Throne with the prophets",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Those who are just will be seated on pulpits of light, near Allah, on the Day of Resurrection, on the right of the Most Merciful — those who are just in their rulings, with their families, and in what they are entrusted with.'",
    source: "Jami' at-Tirmidhi 1330, from Abdullah ibn Amr",
    confidence: "high",
  },
  {
    id: "hadith-107",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 5,
    prompt: "According to a hadith from Abu Hurayrah, where do good dreams come from and where do bad dreams come from?",
    options: [
      "Good dreams from Allah, bad dreams from Shaytan",
      "Good dreams from the angels, bad dreams from the mind",
      "Both come from one's daily thoughts",
      "Both come from food and drink",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Good dreams come from Allah and bad dreams come from Shaytan.' He advised that if one has a bad dream, he should spit to his left three times and seek refuge in Allah from its evil.",
    source: "Sahih Muslim 2263, from Abu Hurayrah",
    confidence: "high",
  },
  {
    id: "hadith-108",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 5,
    prompt: "Until when does Allah accept the repentance of a slave, according to a hadith?",
    options: [
      "Until the soul reaches the throat (at the time of death)",
      "Until the age of forty",
      "Until the middle of one's life",
      "Only until sunrise each day",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Allah accepts the repentance of a slave as long as the soul has not reached the throat.' Repentance is accepted until the moment of death draws near.",
    source: "Jami' at-Tirmidhi 3537, from Abdullah ibn Umar",
    confidence: "high",
  },
  {
    id: "hadith-109",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 5,
    prompt: "In a hadith from Ibn Mas'ud, what did the Prophet say about the distance to Paradise and the Fire?",
    options: [
      "Each is nearer to a person than the lace of his shoe",
      "Each is a long journey away",
      "Paradise is near but the Fire is far",
      "Only the Fire is near",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Paradise is nearer to any of you than the lace of his shoe, and so is the Fire.' Every step of life is a choice between the two.",
    source: "Sahih al-Bukhari 6488, from Abdullah ibn Mas'ud",
    confidence: "high",
  },
  {
    id: "hadith-110",
    pillar: "hadith",
    tier: "intermediate",
    difficulty: 5,
    prompt: "In a hadith from Abu Sa'id al-Khudri, how did the Prophet describe this world?",
    options: [
      "Green and sweet, a temptation to be wary of",
      "Dry and barren, with nothing of value",
      "Dark and gloomy, to be abandoned entirely",
      "Permanent and unchanging",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'The world is green and sweet, and Allah has made you vicegerents in it.' He warned against being deceived by its pleasures, for the world is a place of trial.",
    source: "Sahih Muslim 2742, from Abu Sa'id al-Khudri",
    confidence: "high",
  },
];
