import type { Question } from "@/types";

/**
 * QURAN QUESTIONS — legitimate sources only.
 * Citations use stable surah:ayah numbering (Uthmanic mushaf), which does not
 * vary across editions. Factual claims verified against the Quranic text.
 */
export const quranQuestions: Question[] = [
  // ---- Newbie ----
  {
    id: "quran-001",
    pillar: "quran",
    tier: "newbie",
    difficulty: 1,
    prompt: "Which chapter (surah) opens the Quran?",
    options: ["Al-Fatihah (The Opening)", "An-Nas (Mankind)", "Al-Baqarah (The Cow)", "Al-Ikhlas (Sincerity)"],
    answerIndex: 0,
    explanation:
      "Al-Fatihah is the first surah of the Quran and is recited in every unit of the prayer. Its seven verses are often called 'the Opening'.",
    source: "Quran 1:1–7",
    confidence: "high",
  },
  {
    id: "quran-002",
    pillar: "quran",
    tier: "newbie",
    difficulty: 1,
    prompt: "How many surahs (chapters) does the Quran contain?",
    options: ["114", "100", "120", "110"],
    answerIndex: 0,
    explanation:
      "The Quran contains 114 surahs, beginning with Al-Fatihah and ending with An-Nas. This count is standard across all printed mushafs.",
    source: "Uthmanic mushaf (established count)",
    confidence: "high",
  },
  {
    id: "quran-003",
    pillar: "quran",
    tier: "newbie",
    difficulty: 1,
    prompt: "Which surah is the longest in the Quran?",
    options: ["Al-Baqarah (The Cow)", "Al-Imran (Family of Imran)", "An-Nisa (Women)", "Al-Ma'idah (The Table)"],
    answerIndex: 0,
    explanation:
      "Al-Baqarah (2) is the longest surah in the Quran. Its name refers to the story of the cow related in verses 2:67–73.",
    source: "Quran 2:1–286",
    confidence: "high",
  },
  {
    id: "quran-004",
    pillar: "quran",
    tier: "newbie",
    difficulty: 2,
    prompt: "Which angel brought the revelation of the Quran to the Prophet Muhammad (peace be upon him)?",
    options: ["Jibril", "Mika'il", "Israfil", "Malik"],
    answerIndex: 0,
    explanation:
      "The Quran states that Jibril brought it down to the Prophet's heart. Surah 2:97 names Jibril explicitly as the one who delivers the revelation.",
    source: "Quran 2:97",
    confidence: "high",
  },
  {
    id: "quran-005",
    pillar: "quran",
    tier: "newbie",
    difficulty: 2,
    prompt: "What were the first words of the Quran revealed to the Prophet (peace be upon him)?",
    options: [
      "\"Read, in the name of your Lord who created\"",
      "\"O mankind, worship your Lord\"",
      "\"Praise be to Allah\"",
      "\"The day of judgement\"",
    ],
    answerIndex: 0,
    explanation:
      "The first revelation was the opening of Surah Al-'Alaq: 'Read, in the name of your Lord who created' (96:1). This began in the cave of Hira.",
    source: "Quran 96:1",
    confidence: "high",
  },
  {
    id: "quran-006",
    pillar: "quran",
    tier: "newbie",
    difficulty: 2,
    prompt: "Which surah is the shortest in the Quran?",
    options: ["Al-Kawthar (Abundance)", "Al-Asr (Time)", "Al-Nasr (Victory)", "Al-Ikhlas (Sincerity)"],
    answerIndex: 0,
    explanation:
      "Al-Kawthar (108) is the shortest surah, consisting of three verses. It was revealed to console the Prophet during a difficult time.",
    source: "Quran 108:1–3",
    confidence: "high",
  },
  {
    id: "quran-007",
    pillar: "quran",
    tier: "newbie",
    difficulty: 2,
    prompt: "Over roughly how many years was the Quran revealed?",
    options: ["About 23 years", "About 10 years", "About 30 years", "About 40 years"],
    answerIndex: 0,
    explanation:
      "The Quran was revealed gradually over approximately 23 years, from the first revelation in 610 CE until shortly before the Prophet's death in 632 CE.",
    source: "Established biography of the revelation (seerah)",
    confidence: "high",
  },

  // ---- Average ----
  {
    id: "quran-008",
    pillar: "quran",
    tier: "average",
    difficulty: 3,
    prompt: "In which surah does Ayat al-Kursi (the Throne Verse) appear?",
    options: ["Al-Baqarah (2:255)", "Ya-Sin (36)", "Al-Fatihah (1)", "Al-Mulk (67)"],
    answerIndex: 0,
    explanation:
      "Ayat al-Kursi is verse 2:255 in Surah Al-Baqarah. It describes Allah's sovereignty over the heavens and the earth.",
    source: "Quran 2:255",
    confidence: "high",
  },
  {
    id: "quran-009",
    pillar: "quran",
    tier: "average",
    difficulty: 3,
    prompt: "Which surah is named after an ant, mentioned in one of its verses?",
    options: ["An-Naml (The Ant)", "Al-Ankabut (The Spider)", "Al-Fil (The Elephant)", "An-Nahl (The Bee)"],
    answerIndex: 0,
    explanation:
      "Surah An-Naml (27) takes its name from the ant that warns its colony about Prophet Sulayman (Solomon) in verse 27:18.",
    source: "Quran 27:18",
    confidence: "high",
  },
  {
    id: "quran-010",
    pillar: "quran",
    tier: "average",
    difficulty: 3,
    prompt: "Which woman is the only one named directly in the Quran?",
    options: ["Maryam", "Asiyah", "Khadijah", "Aminah"],
    answerIndex: 0,
    explanation:
      "Maryam (Mary), mother of Prophet 'Isa (Jesus), is the only woman mentioned by name in the Quran. Surah Maryam (19) is named after her.",
    source: "Quran 3:42; 19:16–34",
    confidence: "high",
  },
  {
    id: "quran-011",
    pillar: "quran",
    tier: "average",
    difficulty: 3,
    prompt: "Which two surahs are known together as the Mu'awwidhatayn (the two refuges)?",
    options: ["Al-Falaq and An-Nas", "Al-Ikhlas and Al-Falaq", "Al-Kafirun and Al-Ikhlas", "Al-Baqarah and Al-Imran"],
    answerIndex: 0,
    explanation:
      "Al-Falaq (113) and An-Nas (114) are the two 'refuge' surahs, seeking Allah's protection from evil. They are the final two surahs of the Quran.",
    source: "Quran 113–114",
    confidence: "high",
  },
  {
    id: "quran-012",
    pillar: "quran",
    tier: "average",
    difficulty: 3,
    prompt: "Which prophet is mentioned by name most frequently in the Quran?",
    options: ["Musa (Moses)", "Ibrahim (Abraham)", "Nuh (Noah)", "Yusuf (Joseph)"],
    answerIndex: 0,
    explanation:
      "Musa (Moses) is the prophet mentioned most often in the Quran, with his name appearing around 130 times across many surahs.",
    source: "Established Quranic index/concordance",
    confidence: "high",
  },
  {
    id: "quran-013",
    pillar: "quran",
    tier: "average",
    difficulty: 3,
    prompt: "In which surah is the story of the Companions of the Cave (Ashab al-Kahf) related?",
    options: ["Al-Kahf (The Cave)", "Yusuf (Joseph)", "Al-Anbiya (The Prophets)", "Maryam (Mary)"],
    answerIndex: 0,
    explanation:
      "The story of the young men who slept in the cave is in Surah Al-Kahf (18), verses 9–26. The surah is recommended to be recited on Fridays.",
    source: "Quran 18:9–26",
    confidence: "high",
  },
  {
    id: "quran-014",
    pillar: "quran",
    tier: "average",
    difficulty: 3,
    prompt: "Which surah begins without the basmala (the phrase 'In the name of Allah') at its start?",
    options: ["At-Tawbah (Repentance)", "Al-Fatihah (Opening)", "Al-Mulk (Sovereignty)", "Ya-Sin"],
    answerIndex: 0,
    explanation:
      "At-Tawbah (9) is the only surah that does not begin with the basmala. The basmala appears at the head of every other surah in the standard mushaf.",
    source: "Uthmanic mushaf; Quran 9",
    confidence: "high",
  },

  // ---- Intermediate ----
  {
    id: "quran-015",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 4,
    prompt: "Which verse is generally regarded as the longest single verse in the Quran?",
    options: [
      "Quran 2:282 (the debt verse)",
      "Quran 24:11 (the slander verse)",
      "Quran 5:6 (the wudu verse)",
      "Quran 4:12 (the inheritance verse)",
    ],
    answerIndex: 0,
    explanation:
      "Verse 2:282, dealing with the writing down of debts and contracts, is the longest verse in the Quran.",
    source: "Quran 2:282",
    confidence: "high",
  },
  {
    id: "quran-016",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 4,
    prompt: "In Surah Al-Hijr (15:87), 'the seven oft-repeated verses' (al-sab' al-mathani) refer to which surah?",
    options: ["Al-Fatihah", "Al-Ikhlas", "Al-Kawthar", "Al-Asr"],
    answerIndex: 0,
    explanation:
      "Commentators interpret 'the seven oft-repeated' as Al-Fatihah, which consists of seven verses and is repeated in the daily prayers.",
    source: "Quran 15:87; established tafsir",
    confidence: "high",
  },
  {
    id: "quran-017",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 4,
    prompt: "According to the widely held view, who was Luqman, after whom Surah Luqman is named?",
    options: [
      "A wise man, not a prophet",
      "A prophet of Israel",
      "An angel",
      "A king of Egypt",
    ],
    answerIndex: 0,
    explanation:
      "The dominant view among scholars (the majority opinion) is that Luqman was a wise man granted wisdom, not a prophet. Surah Luqman (31) preserves his advice to his son. A minority of early scholars suggested he was a prophet, but the prevailing position stands.",
    source: "Quran 31:12–19; established tafsir",
    confidence: "high",
  },
  {
    id: "quran-018",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 4,
    prompt: "How many surahs begin with the letters 'Alif Lam Mim'?",
    options: ["Six", "Four", "Eight", "Ten"],
    answerIndex: 0,
    explanation:
      "Six surahs open with the disconnected letters 'Alif Lam Mim': Al-Baqarah (2), Al-Imran (3), Al-Ankabut (29), Ar-Rum (30), Luqman (31), and As-Sajdah (32).",
    source: "Uthmanic mushaf (Quran 2; 3; 29; 30; 31; 32)",
    confidence: "high",
  },
  {
    id: "quran-019",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 5,
    prompt: "In which surah is Dhul-Qarnayn mentioned?",
    options: ["Al-Kahf (The Cave)", "Al-Anbiya (The Prophets)", "Al-Isra (The Night Journey)", "An-Naml (The Ant)"],
    answerIndex: 0,
    explanation:
      "Dhul-Qarnayn, the righteous ruler, is described in Surah Al-Kahf (18:83–98), including the building of the barrier against Gog and Magog.",
    source: "Quran 18:83–98",
    confidence: "high",
  },
  {
    id: "quran-020",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 4,
    prompt: "Which surah takes its name from a spider and the weakness of its web?",
    options: ["Al-Ankabut (The Spider)", "An-Nahl (The Bee)", "Al-Fil (The Elephant)", "An-Naml (The Ant)"],
    answerIndex: 0,
    explanation:
      "Surah Al-Ankabut (29) uses the spider's fragile web in verse 29:41 as a likeness for those who take protectors besides Allah.",
    source: "Quran 29:41",
    confidence: "high",
  },
  {
    id: "quran-021",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 4,
    prompt: "According to Quran 17:1, the Prophet's night journey (al-Isra) was from the Sacred Mosque to which place?",
    options: [
      "Al-Aqsa Mosque (Jerusalem)",
      "Masjid an-Nabawi (Madinah)",
      "The cave of Hira",
      "Mount Sinai",
    ],
    answerIndex: 0,
    explanation:
      "Quran 17:1 states the journey was from the Sacred Mosque (Makkah) to 'the farthest mosque' (al-masjid al-aqsa) in Jerusalem, before the ascension to the heavens.",
    source: "Quran 17:1",
    confidence: "high",
  },

  // ---- Newbie expansion ----
  {
    id: "quran-022",
    pillar: "quran",
    tier: "newbie",
    difficulty: 2,
    prompt: "What is the last (114th) surah of the Quran?",
    options: ["An-Nas (Mankind)", "Al-Falaq (The Dawn)", "Al-Ikhlas (Sincerity)", "Al-Kafirun (The Disbelievers)"],
    answerIndex: 0,
    explanation:
      "The Quran ends with Surah An-Nas (114), the second of the two 'refuge' surahs. It seeks Allah's protection from the whisperings of Satan.",
    source: "Quran 114",
    confidence: "high",
  },
  {
    id: "quran-023",
    pillar: "quran",
    tier: "newbie",
    difficulty: 1,
    prompt: "In which month does the Quran say it was sent down?",
    options: ["Ramadan", "Muharram", "Rajab", "Shawwal"],
    answerIndex: 0,
    explanation:
      "Surah Al-Baqarah states: 'The month of Ramadan in which was revealed the Quran' (2:185). Ramadan is the ninth month of the Islamic calendar.",
    source: "Quran 2:185",
    confidence: "high",
  },
  {
    id: "quran-024",
    pillar: "quran",
    tier: "newbie",
    difficulty: 2,
    prompt:
      "Complete the verse from Surah Al-Qalam: 'And indeed, you [Muhammad] are upon a great —'",
    options: ["Moral character", "Strength", "Wealth", "Knowledge"],
    answerIndex: 0,
    explanation:
      "Quran 68:4 describes the Prophet Muhammad's character: 'And indeed, you are upon a great moral character.' The verse is addressed directly to him.",
    source: "Quran 68:4",
    confidence: "high",
  },
  {
    id: "quran-025",
    pillar: "quran",
    tier: "newbie",
    difficulty: 2,
    prompt: "Which surah is traditionally called 'the Mother of the Quran' (Umm al-Quran)?",
    options: ["Al-Fatihah (The Opening)", "Al-Baqarah (The Cow)", "Al-Ikhlas (Sincerity)", "Ya-Sin"],
    answerIndex: 0,
    explanation:
      "Al-Fatihah is called Umm al-Quran (the Mother of the Quran) and Umm al-Kitab because it summarizes the Quran's core themes and opens the Book.",
    source: "Quran 1:1–7; established designation",
    confidence: "high",
  },
  {
    id: "quran-026",
    pillar: "quran",
    tier: "newbie",
    difficulty: 1,
    prompt: "Which surah tells of the army that came to destroy the Kaaba with elephants?",
    options: ["Al-Fil (The Elephant)", "Al-Fajr (The Dawn)", "Al-Kawthar (Abundance)", "Al-Asr (Time)"],
    answerIndex: 0,
    explanation:
      "Surah Al-Fil (105) recalls how Abraha's army, which marched with elephants, was stopped before reaching the Kaaba. The incident is set in the Year of the Elephant.",
    source: "Quran 105:1–5",
    confidence: "high",
  },
  {
    id: "quran-027",
    pillar: "quran",
    tier: "newbie",
    difficulty: 1,
    prompt: "Which surah is named after the mid-morning light (ad-duha)?",
    options: ["Ad-Duha (The Morning Light)", "Al-Layl (The Night)", "Ash-Shams (The Sun)", "Al-Fajr (The Dawn)"],
    answerIndex: 0,
    explanation:
      "Surah Ad-Duha (93) opens with an oath by the morning light and was revealed to comfort the Prophet during a pause in revelation.",
    source: "Quran 93:1–11",
    confidence: "high",
  },
  {
    id: "quran-028",
    pillar: "quran",
    tier: "newbie",
    difficulty: 1,
    prompt: "In which language does the Quran say it was sent down?",
    options: ["Arabic", "Hebrew", "Aramaic", "Syriac"],
    answerIndex: 0,
    explanation:
      "Surah Yusuf states: 'Indeed, We have sent it down as an Arabic Quran, that you may understand' (12:2). Arabic is the language of the revealed text.",
    source: "Quran 12:2",
    confidence: "high",
  },
  {
    id: "quran-029",
    pillar: "quran",
    tier: "newbie",
    difficulty: 2,
    prompt: "Which short surah is considered the essence of monotheism (tawhid)?",
    options: ["Al-Ikhlas (Sincerity)", "Al-Kafirun (The Disbelievers)", "Al-Falaq (The Dawn)", "An-Nas (Mankind)"],
    answerIndex: 0,
    explanation:
      "Al-Ikhlas (112) declares Allah's oneness: 'Say: He is Allah, the One.' The Prophet described it as equal to a third of the Quran.",
    source: "Quran 112; Sahih al-Bukhari 5013",
    confidence: "high",
  },

  // ---- Average expansion ----
  {
    id: "quran-030",
    pillar: "quran",
    tier: "average",
    difficulty: 3,
    prompt: "In which surah is the full story of Prophet Yusuf (Joseph) related?",
    options: ["Yusuf (12)", "Al-Kahf (18)", "Hud (11)", "Al-Anbiya (The Prophets)"],
    answerIndex: 0,
    explanation:
      "Surah Yusuf (12) tells the whole story of Prophet Yusuf, from the dream to his reunion with his family. The Quran calls it 'the best of stories' (12:3).",
    source: "Quran 12:3–101",
    confidence: "high",
  },
  {
    id: "quran-031",
    pillar: "quran",
    tier: "average",
    difficulty: 3,
    prompt: "Which surah describes the people of the Day of Judgement as 'the companions of the right' and 'the companions of the left'?",
    options: ["Al-Waqi'ah (The Inevitable)", "Al-Mulk (Sovereignty)", "Ar-Rahman (The Merciful)", "Al-Ghashiyah (The Overwhelming)"],
    answerIndex: 0,
    explanation:
      "Surah Al-Waqi'ah (56) divides people on the Day of Judgement into the companions of the right (the blessed) and the companions of the left (the damned).",
    source: "Quran 56:8–9, 27, 41",
    confidence: "high",
  },
  {
    id: "quran-032",
    pillar: "quran",
    tier: "average",
    difficulty: 3,
    prompt: "Which bird brought Prophet Sulayman news of the people of Saba'?",
    options: ["The hoopoe", "The crow", "The raven", "The nightingale"],
    answerIndex: 0,
    explanation:
      "In Surah An-Naml, the hoopoe (hudhud) tells Prophet Sulayman about the people of Saba' worshipping the sun instead of Allah (27:20–28).",
    source: "Quran 27:22–28",
    confidence: "high",
  },
  {
    id: "quran-033",
    pillar: "quran",
    tier: "average",
    difficulty: 3,
    prompt: "Which prophet was cast into a fire that Allah made cool and safe for him?",
    options: ["Ibrahim (Abraham)", "Musa (Moses)", "Yunus (Jonah)", "Ayyub (Job)"],
    answerIndex: 0,
    explanation:
      "Surah Al-Anbiya relates that when Ibrahim was cast into the fire, Allah commanded: 'Be cool and safe for Ibrahim' (21:69).",
    source: "Quran 21:69",
    confidence: "high",
  },
  {
    id: "quran-034",
    pillar: "quran",
    tier: "average",
    difficulty: 3,
    prompt: "In which surah does the story of Prophet Musa and the wise servant Khidr appear?",
    options: ["Al-Kahf (The Cave)", "Al-Isra (The Night Journey)", "Ta-Ha", "Al-Anbiya (The Prophets)"],
    answerIndex: 0,
    explanation:
      "The journey of Musa with Khidr, where Khidr performs seemingly strange acts with hidden wisdom, is related in Surah Al-Kahf (18:60–82).",
    source: "Quran 18:60–82",
    confidence: "high",
  },
  {
    id: "quran-035",
    pillar: "quran",
    tier: "average",
    difficulty: 3,
    prompt: "Which surah begins with the oath 'By the sun and its brightness'?",
    options: ["Ash-Shams (The Sun)", "Al-Layl (The Night)", "Al-Fajr (The Dawn)", "An-Nazi'at (The Pullers)"],
    answerIndex: 0,
    explanation:
      "Surah Ash-Shams (91) opens 'By the sun and its brightness, and the moon when it follows it' (91:1–2), and goes on to purify the soul's path.",
    source: "Quran 91:1–15",
    confidence: "high",
  },
  {
    id: "quran-036",
    pillar: "quran",
    tier: "average",
    difficulty: 3,
    prompt: "In which surah does the verse 'O you who believe, seek help through patience and prayer' appear?",
    options: ["Al-Baqarah (The Cow)", "Al-Imran (Family of Imran)", "An-Nisa (Women)", "Al-Ma'idah (The Table)"],
    answerIndex: 0,
    explanation:
      "The command to seek help through patience and prayer is in Surah Al-Baqarah (2:153), addressed to those who believe.",
    source: "Quran 2:153",
    confidence: "high",
  },
  {
    id: "quran-037",
    pillar: "quran",
    tier: "average",
    difficulty: 3,
    prompt: "A person who has memorized the entire Quran is called a —",
    options: ["Hafiz", "Qari", "Mu'adhdhin", "Khatib"],
    answerIndex: 0,
    explanation:
      "A hafiz has memorized the whole Quran. A qari is a reciter, a mu'adhdhin calls the adhan, and a khatib delivers the Friday sermon.",
    source: "Established Islamic terminology",
    confidence: "high",
  },

  // ---- Intermediate expansion ----
  {
    id: "quran-038",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 3,
    prompt: "The Quran is divided into 30 sections called —",
    options: ["Ajza' (juz')", "Ahzab (hizb)", "Ruku'", "Sajdah"],
    answerIndex: 0,
    explanation:
      "For reading, the Quran is divided into 30 roughly equal parts called ajza' (singular juz'), making it practical to complete in a month.",
    source: "Established mushaf convention",
    confidence: "high",
  },
  {
    id: "quran-039",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 4,
    prompt: "In which surah does the Quran declare that 'no falsehood approaches it from before it or from behind it'?",
    options: ["Fussilat (Explained in Detail)", "Al-Hijr (The Stone Land)", "Al-Waqi'ah (The Inevitable)", "Al-Baqarah (The Cow)"],
    answerIndex: 0,
    explanation:
      "Surah Fussilat (41:42) states the Quran is protected from falsehood 'from before it and from behind it' — a revelation from the One worthy of praise.",
    source: "Quran 41:42",
    confidence: "high",
  },
  {
    id: "quran-040",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 5,
    prompt: "In Surah Al-Buruj (85), the 'companions of the ditch' (Ashab al-Ukhdud) were —",
    options: [
      "Believers thrown into a fire for their faith",
      "A people of a well who rejected a messenger",
      "A giant nation destroyed by a sandstorm",
      "The builders of the Kaaba",
    ],
    answerIndex: 0,
    explanation:
      "Al-Buruj (85:4–8) describes believers who were cast into a trench of fire by a tyrant king because they refused to renounce their faith in Allah.",
    source: "Quran 85:4–8",
    confidence: "high",
  },
  {
    id: "quran-041",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 4,
    prompt: "In which surah is the Prophet described as 'the Seal of the Prophets'?",
    options: ["Al-Ahzab (The Confederates)", "Al-Ma'idah (The Table)", "Al-Anbiya (The Prophets)", "Al-Baqarah (The Cow)"],
    answerIndex: 0,
    explanation:
      "Surah Al-Ahzab (33:40) calls Muhammad 'the Messenger of Allah and the Seal of the Prophets' — the final prophet after whom no prophet follows.",
    source: "Quran 33:40",
    confidence: "high",
  },
  {
    id: "quran-042",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 5,
    prompt: "In the standard mushaf, each juz' of the Quran is further divided into how many hizb?",
    options: ["Two", "Three", "Four", "Five"],
    answerIndex: 0,
    explanation:
      "Each juz' is split into two hizb, giving 60 hizb across the whole Quran — a common marker system for recitation milestones.",
    source: "Established mushaf convention",
    confidence: "high",
  },
  {
    id: "quran-043",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 5,
    prompt: "Which two surahs are together called 'Az-Zahrawan' (the two luminous ones)?",
    options: [
      "Al-Baqarah and Al-Imran",
      "Al-Falaq and An-Nas",
      "Al-Ikhlas and Al-Falaq",
      "Al-Mulk and Ya-Sin",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet called Al-Baqarah and Al-Imran 'Az-Zahrawan' (the two luminous ones); on the Day of Judgement they will shade those who recited them.",
    source: "Sahih Muslim 804; Quran 2–3",
    confidence: "high",
  },
  {
    id: "quran-044",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 4,
    prompt: "In which surah does Allah say 'We will show them Our signs in the horizons and in themselves'?",
    options: ["Fussilat (Explained in Detail)", "Al-Ghashiyah (The Overwhelming)", "Ar-Rum (The Romans)", "Al-Ankabut (The Spider)"],
    answerIndex: 0,
    explanation:
      "Surah Fussilat (41:53) promises that Allah will show His signs 'in the horizons and within themselves' until the truth becomes clear.",
    source: "Quran 41:53",
    confidence: "high",
  },
  {
    id: "quran-045",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 5,
    prompt: "How many surahs of the Quran are named after a single prophet?",
    options: ["Six", "Seven", "Five", "Eight"],
    answerIndex: 0,
    explanation:
      "Six surahs carry a prophet's name: Yunus (10), Hud (11), Yusuf (12), Ibrahim (14), Muhammad (47), and Nuh (71). (Al-Anbiya, 'The Prophets', is plural.)",
    source: "Uthmanic mushaf (Quran 10; 11; 12; 14; 47; 71)",
    confidence: "high",
  },
  {
    id: "quran-046",
    pillar: "quran",
    tier: "newbie",
    difficulty: 3,
    prompt: "In which surah does the basmala ('In the name of Allah, the Most Gracious, the Most Merciful') appear twice as a full verse?",
    options: ["An-Naml (The Ant)", "Al-A'raf (The Heights)", "Yusuf (Joseph)", "An-Naba (The Tidings)"],
    answerIndex: 0,
    explanation:
      "The basmala appears as an explicit verse in two places: as the opening of Al-Fatihah (1:1) and inside Surah An-Naml (27:30), at the head of Prophet Sulayman's letter to the Queen of Sheba.",
    source: "Quran 27:30",
    confidence: "high",
  },
  {
    id: "quran-047",
    pillar: "quran",
    tier: "newbie",
    difficulty: 2,
    prompt: "Which surah opens with the oath 'By the fig and the olive'?",
    options: ["At-Tin (The Fig)", "Al-Qalam (The Pen)", "Al-Alaq (The Clot)", "Al-Balad (The City)"],
    answerIndex: 0,
    explanation:
      "Surah At-Tin (95:1) swears 'By the fig and the olive, and by Mount Sinai'. Scholars interpret these as the lands where Prophet 'Isa and Prophet Musa received revelation.",
    source: "Quran 95:1",
    confidence: "high",
  },
  {
    id: "quran-048",
    pillar: "quran",
    tier: "newbie",
    difficulty: 2,
    prompt: "Which surah has the name 'the Most Merciful' (Ar-Rahman) as its very first word?",
    options: ["Ar-Rahman", "Al-Fatihah", "Al-Ikhlas", "Al-Mulk"],
    answerIndex: 0,
    explanation:
      "Surah Ar-Rahman (55:1) begins directly with the divine name: 'Ar-Rahman' (the Most Merciful). The surah is famous for the repeated refrain 'Which of the favors of your Lord will you deny?'",
    source: "Quran 55:1",
    confidence: "high",
  },
  {
    id: "quran-049",
    pillar: "quran",
    tier: "newbie",
    difficulty: 3,
    prompt: "In which surah is the story of the two sons of Adam — whose offering Allah accepted from one but not the other — related?",
    options: ["Al-Ma'idah (The Table Spread)", "Al-Baqarah (The Cow)", "An-Nisa (The Women)", "Al-An'am (The Cattle)"],
    answerIndex: 0,
    explanation:
      "Surah Al-Ma'idah (5:27-31) tells of the two sons of Adam: the jealous one slew his brother, then 'became among the regretful' after seeing a crow scratch the earth to show him how to bury him.",
    source: "Quran 5:27-31",
    confidence: "high",
  },
  {
    id: "quran-050",
    pillar: "quran",
    tier: "average",
    difficulty: 3,
    prompt: "Which surah contains the supplication of Prophet Yunus: 'There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers'?",
    options: ["Al-Anbiya (The Prophets)", "Yunus (Jonah)", "As-Saffat (Those Ranged in Ranks)", "An-Naml (The Ant)"],
    answerIndex: 0,
    explanation:
      "The famous 'du'a of the fish' is Quran 21:87, in Surah Al-Anbiya, where Yunus calls out from the darkness of the fish's belly. The same verse notes that Allah 'will rescue him from distress'.",
    source: "Quran 21:87",
    confidence: "high",
  },
  {
    id: "quran-051",
    pillar: "quran",
    tier: "average",
    difficulty: 3,
    prompt: "Which surah says that the Night of Power (Laylat al-Qadr) is 'better than a thousand months'?",
    options: ["Al-Qadr (The Decree)", "Al-Baqarah (The Cow)", "Ad-Dukhan (The Smoke)", "Al-Mulk (The Sovereignty)"],
    answerIndex: 0,
    explanation:
      "Surah Al-Qadr (97:1-3) states the Quran was sent down on the Night of Power and that this night is better than a thousand months. It falls in the last ten nights of Ramadan.",
    source: "Quran 97:1-3",
    confidence: "high",
  },
  {
    id: "quran-052",
    pillar: "quran",
    tier: "average",
    difficulty: 3,
    prompt: "Which surah did the Prophet call 'the heart of the Quran'?",
    options: ["Ya-Sin", "Al-Baqarah", "Al-Fatihah", "Al-Mulk"],
    answerIndex: 0,
    explanation:
      "The Prophet said: 'Everything has a heart, and the heart of the Quran is Ya-Sin.' Surah Ya-Sin is the 36th surah and is recited widely for the deceased.",
    source: "Quran 36; Jami' at-Tirmidhi 2887",
    confidence: "high",
  },
  {
    id: "quran-053",
    pillar: "quran",
    tier: "average",
    difficulty: 4,
    prompt: "In which surah does Allah say, 'I did not create the jinn and mankind except to worship Me'?",
    options: ["Adh-Dhariyat (The Winnowing Winds)", "Ar-Rahman (The Most Merciful)", "Al-Jinn (The Jinn)", "An-Najm (The Star)"],
    answerIndex: 0,
    explanation:
      "Quran 51:56 (Surah Adh-Dhariyat) gives the purpose of creation: to worship Allah alone. Classical commentators hold 'worship' here includes knowing Him.",
    source: "Quran 51:56",
    confidence: "high",
  },
  {
    id: "quran-054",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 4,
    prompt: "How many prophets are mentioned by name in the Quran?",
    options: ["25", "28", "40", "124,000"],
    answerIndex: 0,
    explanation:
      "Twenty-five prophets are named in the Quran (the total number of prophets sent is far greater — a hadith mentions 124,000). The names range from Adam to Muhammad (peace be upon them all).",
    source: "Quran (names throughout the mushaf); established scholarly count",
    confidence: "high",
  },
  {
    id: "quran-055",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 4,
    prompt: "In which surah does Allah say, 'And your Lord has decreed that you not worship except Him, and to parents, good treatment'?",
    options: ["Al-Isra (The Night Journey)", "Luqman", "Al-Ahqaf (The Sand Dunes)", "Al-Ankabut (The Spider)"],
    answerIndex: 0,
    explanation:
      "Quran 17:23 (Surah Al-Isra) joins the command to worship Allah alone with kindness to parents, and goes on to forbid even saying 'uff' to them.",
    source: "Quran 17:23",
    confidence: "high",
  },
  {
    id: "quran-056",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 5,
    prompt: "In which surah does Allah say, 'And We place the scales of justice for the Day of Resurrection, so no soul will be treated unjustly'?",
    options: ["Al-Anbiya (The Prophets)", "Al-A'raf (The Heights)", "Az-Zalzalah (The Earthquake)", "An-Nisa (The Women)"],
    answerIndex: 0,
    explanation:
      "Quran 21:47 (Surah Al-Anbiya) describes the scales of justice on the Day of Judgement, weighing even a mustard seed. (Al-A'raf also mentions scales, but at 7:8-9.)",
    source: "Quran 21:47",
    confidence: "high",
  },
  {
    id: "quran-057",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 4,
    prompt: "Which surah opens with the question 'About what are they asking one another?'",
    options: ["An-Naba (The Tidings)", "Al-Mursalat (Those Sent Forth)", "At-Takwir (The Overthrowing)", "Al-Fajr (The Dawn)"],
    answerIndex: 0,
    explanation:
      "Surah An-Naba (78:1-4) opens with 'About what are they asking one another?' and answers: about the great news — the resurrection and the Day of Judgement, which the disbelievers denied.",
    source: "Quran 78:1-4",
    confidence: "high",
  },
  {
    id: "quran-058",
    pillar: "quran",
    tier: "newbie",
    difficulty: 1,
    prompt: "In which surah do Muslims recite the supplication 'Guide us to the straight path' in every prayer?",
    options: ["Al-Fatihah (The Opening)", "Al-Ikhlas (The Sincerity)", "Al-Kawthar (The Abundance)", "An-Nas (The Mankind)"],
    answerIndex: 0,
    explanation:
      "Al-Fatihah (1:6) contains the prayer 'Guide us to the straight path'. Since it is recited in every unit of prayer, this verse is among the most-repeated in the Quran.",
    source: "Quran 1:6",
    confidence: "high",
  },
  {
    id: "quran-059",
    pillar: "quran",
    tier: "newbie",
    difficulty: 3,
    prompt: "Which surah opens with the oath 'I swear by the Day of Resurrection'?",
    options: ["Al-Qiyamah (The Resurrection)", "Al-Ghashiyah (The Overwhelming)", "At-Takwir (The Overthrowing)", "Ad-Duha (The Morning Brightness)"],
    answerIndex: 0,
    explanation:
      "Surah Al-Qiyamah (75:1) opens: 'I swear by the Day of Resurrection.' It deals with the certainty of resurrection and the fate of souls.",
    source: "Quran 75:1",
    confidence: "high",
  },
  {
    id: "quran-060",
    pillar: "quran",
    tier: "newbie",
    difficulty: 3,
    prompt: "In which surah does Allah promise to preserve the Quran: 'Indeed, We have sent down the Reminder, and indeed, We are its Guardian'?",
    options: ["Al-Hijr (The Stoneland)", "Al-Baqarah (The Cow)", "Yunus (Jonah)", "Az-Zumar (The Groups)"],
    answerIndex: 0,
    explanation:
      "Quran 15:9 (Surah Al-Hijr) is the verse of preservation: Allah sent down the Reminder and guarantees to guard it from corruption.",
    source: "Quran 15:9",
    confidence: "high",
  },
  {
    id: "quran-061",
    pillar: "quran",
    tier: "newbie",
    difficulty: 2,
    prompt: "Which surah repeats the assurance 'Indeed, with hardship comes ease'?",
    options: ["Ash-Sharh (The Relief)", "Al-Layl (The Night)", "Al-Balad (The City)", "Al-Kawthar (The Abundance)"],
    answerIndex: 0,
    explanation:
      "Surah Ash-Sharh (94:5-6) states twice: 'Indeed, with hardship comes ease' — a source of comfort and hope for believers. (Ash-Sharh is also known as Al-Inshirah.)",
    source: "Quran 94:5-6",
    confidence: "high",
  },
  {
    id: "quran-062",
    pillar: "quran",
    tier: "average",
    difficulty: 4,
    prompt: "In which surah does Allah instruct the Prophet to consult his companions in matters?",
    options: ["Al-Imran (The Family of Imran)", "Al-Anfal (The Spoils of War)", "Ash-Shura (The Consultation)", "Al-Mujadila (The Pleading Woman)"],
    answerIndex: 0,
    explanation:
      "Quran 3:159 (Surah Al-Imran) tells the Prophet: '...and consult them in the affair.' Ash-Shura is named after consultation, but this specific instruction is in Al-Imran.",
    source: "Quran 3:159",
    confidence: "high",
  },
  {
    id: "quran-063",
    pillar: "quran",
    tier: "average",
    difficulty: 4,
    prompt: "Which surah is named after the people who stand between Paradise and Hell, whose occupants are described there?",
    options: ["Al-A'raf (The Heights)", "Al-Mulk (The Sovereignty)", "Al-Furqan (The Criterion)", "Al-Haqqah (The Reality)"],
    answerIndex: 0,
    explanation:
      "Surah Al-A'raf (7:46-47) describes the people of the Heights (al-A'raf) — those whose scales are balanced, standing between Paradise and Hell awaiting entry.",
    source: "Quran 7:46-47",
    confidence: "high",
  },
  {
    id: "quran-064",
    pillar: "quran",
    tier: "average",
    difficulty: 4,
    prompt: "Which surah repeats four times: 'And We have certainly made the Quran easy to remember — so is there any who will be reminded?'",
    options: ["Al-Qamar (The Moon)", "Ar-Rahman (The Most Merciful)", "Al-Mursalat (Those Sent Forth)", "Abasa (He Frowned)"],
    answerIndex: 0,
    explanation:
      "Surah Al-Qamar (54:17, 22, 32, 40) repeats the refrain about the Quran being made easy for remembrance — four times, once after each punishment story.",
    source: "Quran 54:17, 22, 32, 40",
    confidence: "high",
  },
  {
    id: "quran-065",
    pillar: "quran",
    tier: "average",
    difficulty: 4,
    prompt: "In which surah does Allah say He 'sent down iron, wherein is great might and benefits for mankind'?",
    options: ["Al-Hadid (The Iron)", "Al-Fath (The Victory)", "An-Naml (The Ant)", "As-Saff (The Ranks)"],
    answerIndex: 0,
    explanation:
      "Surah Al-Hadid (57:25) mentions iron sent down with 'great might and benefits for mankind'. It is the surah named 'The Iron'.",
    source: "Quran 57:25",
    confidence: "high",
  },
  {
    id: "quran-066",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 5,
    prompt: "In which surah do Pharaoh's sorcerers cast their staffs and ropes, then fall prostrate upon recognising the truth?",
    options: ["Ta-Ha", "Yusuf (Joseph)", "Al-Kahf (The Cave)", "Al-Qasas (The Stories)"],
    answerIndex: 0,
    explanation:
      "In Surah Ta-Ha (20:65-70), the sorcerers cast their ropes and staffs, then after Musa's staff swallowed them, they fell prostrate, declaring faith in the Lord of Musa and Harun.",
    source: "Quran 20:65-70",
    confidence: "high",
  },
  {
    id: "quran-067",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 5,
    prompt: "In which surah does Allah describe Himself as 'Lord of the two easts and Lord of the two wests'?",
    options: ["Ar-Rahman (The Most Merciful)", "Al-An'am (The Cattle)", "Al-Ma'arij (The Ascending Stairways)", "An-Nazi'at (Those Who Pull Out)"],
    answerIndex: 0,
    explanation:
      "Quran 55:17 (Surah Ar-Rahman) reads 'Lord of the two easts and Lord of the two wests' — the extreme points of the sunrise and sunset across the year.",
    source: "Quran 55:17",
    confidence: "high",
  },
  {
    id: "quran-068",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 4,
    prompt: "Which surah describes a visible smoke (dukhan) coming over the sky as a sign of punishment?",
    options: ["Ad-Dukhan (The Smoke)", "Al-Waqi'ah (The Event)", "An-Najm (The Star)", "At-Tur (The Mount)"],
    answerIndex: 0,
    explanation:
      "Surah Ad-Dukhan (44:10) says: 'Then watch for the Day when the sky will bring a visible smoke.' Some commentators connect it to the famine or a sign before the Hour.",
    source: "Quran 44:10",
    confidence: "high",
  },
  {
    id: "quran-069",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 5,
    prompt: "Which surah says 'The believers are but brothers, so make peace between your brothers'?",
    options: ["Al-Hujurat (The Chambers)", "An-Nisa (The Women)", "Al-Ma'idah (The Table Spread)", "Al-Anfal (The Spoils of War)"],
    answerIndex: 0,
    explanation:
      "Surah Al-Hujurat (49:10) establishes the brotherhood of believers and commands reconciliation. The surah is named after the chambers of the Prophet's wives, with etiquette for his household.",
    source: "Quran 49:10",
    confidence: "high",
  },
  {
    id: "quran-070",
    pillar: "quran",
    tier: "newbie",
    difficulty: 3,
    prompt: "Which surah opens with 'Nun. By the pen and what they write'?",
    options: ["Al-Qalam (The Pen)", "Al-Alaq (The Clot)", "Al-Bayyinah (The Clear Proof)", "Al-Humazah (The Slanderer)"],
    answerIndex: 0,
    explanation:
      "Surah Al-Qalam (68:1) opens with the single letter 'Nun' and an oath by the pen — a tribute to writing and knowledge. It is one of the surahs of the disjointed letters.",
    source: "Quran 68:1",
    confidence: "high",
  },
  {
    id: "quran-071",
    pillar: "quran",
    tier: "newbie",
    difficulty: 3,
    prompt: "Which surah opens with the oath 'By the star when it descends'?",
    options: ["An-Najm (The Star)", "Al-Ma'arij (The Ascending Stairways)", "At-Tariq (The Night Comer)", "Ash-Shams (The Sun)"],
    answerIndex: 0,
    explanation:
      "Surah An-Najm (53:1) opens: 'By the star when it descends.' It includes the account of the Prophet's vision of the revelation and the night journey.",
    source: "Quran 53:1",
    confidence: "high",
  },
  {
    id: "quran-072",
    pillar: "quran",
    tier: "newbie",
    difficulty: 2,
    prompt: "Which surah opens with the oath 'By the dawn'?",
    options: ["Al-Fajr (The Dawn)", "Al-Ghashiyah (The Overwhelming)", "Al-Balad (The City)", "Al-Layl (The Night)"],
    answerIndex: 0,
    explanation:
      "Surah Al-Fajr (89:1) swears 'By the dawn' — and goes on to mention 'the ten nights' and the fate of earlier nations, warning against greed and injustice.",
    source: "Quran 89:1",
    confidence: "high",
  },
  {
    id: "quran-073",
    pillar: "quran",
    tier: "newbie",
    difficulty: 2,
    prompt: "Which surah opens with the oath 'By the night when it covers'?",
    options: ["Al-Layl (The Night)", "Al-Fajr (The Dawn)", "Al-Asr (The Time)", "Ad-Duha (The Morning Brightness)"],
    answerIndex: 0,
    explanation:
      "Surah Al-Layl (92:1) swears 'By the night when it covers', contrasting those who give and fear Allah with those who withhold and deny.",
    source: "Quran 92:1",
    confidence: "high",
  },
  {
    id: "quran-074",
    pillar: "quran",
    tier: "average",
    difficulty: 4,
    prompt: "In which surah does Allah say He sent no messenger except with the language of his own people?",
    options: ["Ibrahim (Abraham)", "Ash-Shu'ara (The Poets)", "Ar-Rum (The Romans)", "An-Nahl (The Bee)"],
    answerIndex: 0,
    explanation:
      "Quran 14:4 (Surah Ibrahim) states that every messenger was sent with the language of his people, so the message could be made clear to them.",
    source: "Quran 14:4",
    confidence: "high",
  },
  {
    id: "quran-075",
    pillar: "quran",
    tier: "average",
    difficulty: 4,
    prompt: "In which surah does Allah say 'And We made from water every living thing'?",
    options: ["Al-Anbiya (The Prophets)", "An-Nur (The Light)", "Al-Furqan (The Criterion)", "Yasin"],
    answerIndex: 0,
    explanation:
      "Quran 21:30 (Surah Al-Anbiya) says every living thing was made from water — a statement early Muslims could only take on faith, and one modern biology corroborates.",
    source: "Quran 21:30",
    confidence: "high",
  },
  {
    id: "quran-076",
    pillar: "quran",
    tier: "average",
    difficulty: 4,
    prompt: "Which surah contains the verse 'O you who have believed, fasting has been prescribed for you as it was prescribed for those before you'?",
    options: ["Al-Baqarah (The Cow)", "An-Nisa (The Women)", "Al-Ma'idah (The Table Spread)", "Luqman"],
    answerIndex: 0,
    explanation:
      "Quran 2:183 (Surah Al-Baqarah) commands fasting for the believers, noting it was prescribed for those before them — the verse that introduces the obligation of Ramadan.",
    source: "Quran 2:183",
    confidence: "high",
  },
  {
    id: "quran-077",
    pillar: "quran",
    tier: "average",
    difficulty: 4,
    prompt: "Which surah says 'who created the seven heavens in layers'?",
    options: ["Al-Mulk (The Sovereignty)", "Al-An'am (The Cattle)", "Az-Zumar (The Groups)", "Ghafir (The Forgiver)"],
    answerIndex: 0,
    explanation:
      "Surah Al-Mulk (67:3) describes Allah creating 'the seven heavens in layers', then asks: 'Do you see in the creation of the Most Merciful any inconsistency?'",
    source: "Quran 67:3",
    confidence: "high",
  },
  {
    id: "quran-078",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 5,
    prompt: "In which surah does Allah say 'Every soul shall taste death, and you will only be given your full compensation on the Day of Resurrection'?",
    options: ["Al-Imran (The Family of Imran)", "An-Nisa (The Women)", "Al-Hadid (The Iron)", "Yusuf (Joseph)"],
    answerIndex: 0,
    explanation:
      "Quran 3:185 (Surah Al-Imran) declares that every soul will taste death and that full recompense comes on the Day of Resurrection — whoever is saved from the Fire and admitted to Paradise has succeeded.",
    source: "Quran 3:185",
    confidence: "high",
  },
  {
    id: "quran-079",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 5,
    prompt: "Which surah contains Ayat an-Nur, the 'Verse of Light' — 'Allah is the Light of the heavens and the earth'?",
    options: ["An-Nur (The Light)", "Al-Mulk (The Sovereignty)", "Ar-Rahman (The Most Merciful)", "Al-Ikhlas (The Sincerity)"],
    answerIndex: 0,
    explanation:
      "Surah An-Nur (24:35) contains the famous parable of light: Allah as the Light of the heavens and earth, likened to a niche with a shining lamp. It is one of the most commented-upon verses in the Quran.",
    source: "Quran 24:35",
    confidence: "high",
  },
  {
    id: "quran-080",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 5,
    prompt: "In which surah are the two angels Harut and Marut mentioned in connection with the magic of Babylon?",
    options: ["Al-Baqarah (The Cow)", "Al-A'raf (The Heights)", "Yunus (Jonah)", "Al-Jinn (The Jinn)"],
    answerIndex: 0,
    explanation:
      "Surah Al-Baqarah (2:102) mentions Harut and Marut, two angels sent to test the people of Babylon, who taught what was a trial — not to be used to harm others.",
    source: "Quran 2:102",
    confidence: "high",
  },
  {
    id: "quran-081",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 4,
    prompt: "Which surah takes its name from the cow that Bani Israel were commanded to sacrifice?",
    options: ["Al-Baqarah (The Cow)", "Al-An'am (The Cattle)", "Al-Ma'idah (The Table Spread)", "Al-Nahl (The Bee)"],
    answerIndex: 0,
    explanation:
      "Surah Al-Baqarah is named after the story in 2:67-73, where Bani Israel were commanded to sacrifice a cow to uncover the truth of a murder.",
    source: "Quran 2:67-73",
    confidence: "high",
  },
  {
    id: "quran-082",
    pillar: "quran",
    tier: "newbie",
    difficulty: 3,
    prompt: "Which surah is named after the believers and disbelievers being led in groups — one group to Paradise and one to Hell?",
    options: ["Az-Zumar (The Groups)", "Al-Furqan (The Criterion)", "An-Najm (The Star)", "Al-Ma'arij (The Ascending Stairways)"],
    answerIndex: 0,
    explanation:
      "Surah Az-Zumar (39) takes its name from the imagery of groups (zumur): the believers led to Paradise in procession and the disbelievers to Hell.",
    source: "Quran 39 (name and themes)",
    confidence: "high",
  },
  {
    id: "quran-083",
    pillar: "quran",
    tier: "newbie",
    difficulty: 3,
    prompt: "Which surah is named after the divine attribute 'the Forgiver' (Al-Ghafir)?",
    options: ["Ghafir (The Forgiver)", "Al-Hadi (The Guide)", "Al-Wahhab (The Bestower)", "Ar-Razzaq (The Provider)"],
    answerIndex: 0,
    explanation:
      "Surah Ghafir (40) is named after the attribute 'the Forgiver', from the verse 'Forgiver of sin, acceptor of repentance' (40:3).",
    source: "Quran 40:1-3",
    confidence: "high",
  },
  {
    id: "quran-084",
    pillar: "quran",
    tier: "newbie",
    difficulty: 2,
    prompt: "Which surah describes the earth's violent shaking on the Last Day, when it brings out its burdens?",
    options: ["Az-Zalzalah (The Earthquake)", "Al-Qari'ah (The Striking Calamity)", "Al-Haqqah (The Reality)", "Al-Waqi'ah (The Event)"],
    answerIndex: 0,
    explanation:
      "Surah Az-Zalzalah (99) opens: 'When the earth is shaken with its shaking, and the earth brings out its burdens' — and then every atom's weight of good and evil is shown.",
    source: "Quran 99:1-8",
    confidence: "high",
  },
  {
    id: "quran-085",
    pillar: "quran",
    tier: "newbie",
    difficulty: 3,
    prompt: "Which surah says 'Indeed, We created man from a drop of mixed fluid so that We may test him'?",
    options: ["Al-Insan (The Man)", "At-Tin (The Fig)", "Al-Alaq (The Clot)", "Al-Mursalat (Those Sent Forth)"],
    answerIndex: 0,
    explanation:
      "Surah Al-Insan (76:2) speaks of creating man from a drop of mixed fluid to test him, and describes the reward of the righteous in Paradise.",
    source: "Quran 76:2",
    confidence: "high",
  },
  {
    id: "quran-086",
    pillar: "quran",
    tier: "average",
    difficulty: 4,
    prompt: "Which surah is named after the 'Criterion' (Al-Furqan) that separates truth from falsehood — one of the names of the Quran?",
    options: ["Al-Furqan (The Criterion)", "Al-Kitab (The Book)", "Al-Tanzil (The Revelation)", "As-Sirat (The Path)"],
    answerIndex: 0,
    explanation:
      "Surah Al-Furqan (25) is named after the Quran's attribute as 'the Criterion' — the standard that distinguishes truth from falsehood.",
    source: "Quran 25 (name); 25:1",
    confidence: "high",
  },
  {
    id: "quran-087",
    pillar: "quran",
    tier: "average",
    difficulty: 4,
    prompt: "In which surah does Allah say He sent down the Reminder to the Prophet so he could make clear to the people what was revealed to them?",
    options: ["An-Nahl (The Bee)", "Al-Ankabut (The Spider)", "Al-Qasas (The Stories)", "Al-Hijr (The Stoneland)"],
    answerIndex: 0,
    explanation:
      "Quran 16:44 (Surah An-Nahl) says the Reminder was sent down so the Prophet could make clear to the people what was revealed to them — the basis of the Prophet's role as explainer.",
    source: "Quran 16:44",
    confidence: "high",
  },
  {
    id: "quran-088",
    pillar: "quran",
    tier: "average",
    difficulty: 4,
    prompt: "Which surah relates how a group of jinn listened to the Quran and embraced faith?",
    options: ["Al-Jinn (The Jinn)", "Ar-Rahman (The Most Merciful)", "An-Najm (The Star)", "Al-Falaq (The Daybreak)"],
    answerIndex: 0,
    explanation:
      "Surah Al-Jinn (72) opens with a group of jinn hearing the Quran, saying 'Indeed, we have heard a wondrous Quran' and believing in it.",
    source: "Quran 72:1-2",
    confidence: "high",
  },
  {
    id: "quran-089",
    pillar: "quran",
    tier: "average",
    difficulty: 4,
    prompt: "In which surah is the verse 'Indeed, prayer prohibits immorality and wrongdoing, and the remembrance of Allah is greater'?",
    options: ["Al-Ankabut (The Spider)", "Al-Baqarah (The Cow)", "Al-Ma'idah (The Table Spread)", "At-Tawbah (The Repentance)"],
    answerIndex: 0,
    explanation:
      "Quran 29:45 (Surah Al-Ankabut) says prayer prohibits immorality and wrongdoing, and that the remembrance of Allah is greater — a key verse on the purpose of salah.",
    source: "Quran 29:45",
    confidence: "high",
  },
  {
    id: "quran-090",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 4,
    prompt: "Which surah is named 'The Stories' (Al-Qasas) and tells of Musa's infancy and his journey to Midian?",
    options: ["Al-Qasas (The Stories)", "Ta-Ha", "Ash-Shu'ara (The Poets)", "Al-Mumtahanah (The Examined Woman)"],
    answerIndex: 0,
    explanation:
      "Surah Al-Qasas (28) relates the 'stories' of Musa — his mother casting him in the river, his rescue by Pharaoh's household, and his flight to Midian.",
    source: "Quran 28 (name and themes)",
    confidence: "high",
  },
  {
    id: "quran-091",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 5,
    prompt: "Which surah is named 'The Gathering' (Al-Hashr), after the expulsion of a Jewish tribe from Madinah?",
    options: ["Al-Hashr (The Gathering)", "Al-Anfal (The Spoils of War)", "Al-Fath (The Victory)", "Al-Munafiqun (The Hypocrites)"],
    answerIndex: 0,
    explanation:
      "Surah Al-Hashr (59) opens with the gathering and expulsion of the Banu Nadir, who had conspired against the Prophet in Madinah.",
    source: "Quran 59 (name and themes)",
    confidence: "high",
  },
  {
    id: "quran-092",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 5,
    prompt: "In which surah does Allah say 'And hold fast, all together, to the rope of Allah, and do not be divided'?",
    options: ["Al-Imran (The Family of Imran)", "An-Nisa (The Women)", "Al-Anfal (The Spoils of War)", "Al-Ma'idah (The Table Spread)"],
    answerIndex: 0,
    explanation:
      "Quran 3:103 (Surah Al-Imran) commands believers to hold fast together to the rope of Allah and not be divided — recalling how Allah united their hearts.",
    source: "Quran 3:103",
    confidence: "high",
  },
  {
    id: "quran-093",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 5,
    prompt: "In which surah does Allah command 'O you who believe, stand firm for justice, as witnesses for Allah, even if it be against yourselves'?",
    options: ["An-Nisa (The Women)", "Al-Imran (The Family of Imran)", "Al-Mumtahanah (The Examined Woman)", "At-Tawbah (The Repentance)"],
    answerIndex: 0,
    explanation:
      "Quran 4:135 (Surah An-Nisa) commands standing firmly for justice as witnesses for Allah, even against oneself, one's parents, or close relatives — with wealth and poverty making no difference.",
    source: "Quran 4:135",
    confidence: "high",
  },
  {
    id: "quran-094",
    pillar: "quran",
    tier: "newbie",
    difficulty: 3,
    prompt: "Which surah opens 'Blessed is He in whose hand is the dominion, and He over all things has power'?",
    options: ["Al-Mulk (The Sovereignty)", "Al-Hadid (The Iron)", "Al-Haqqah (The Reality)", "Al-Qiyamah (The Resurrection)"],
    answerIndex: 0,
    explanation:
      "Surah Al-Mulk (67:1) opens: 'Blessed is He in whose hand is the dominion.' It is highly recommended to recite each night and is said to intercede for its reader.",
    source: "Quran 67:1",
    confidence: "high",
  },
  {
    id: "quran-095",
    pillar: "quran",
    tier: "newbie",
    difficulty: 3,
    prompt: "Which surah opens 'Exalt the name of your Lord, the Most High'?",
    options: ["Al-A'la (The Most High)", "Al-A'raf (The Heights)", "Al-Ala", "At-Taghabun (The Mutual Disillusion)"],
    answerIndex: 0,
    explanation:
      "Surah Al-A'la (87:1) begins with glorifying the name of the Most High. The Prophet would recite it and Al-Ghashiyah in the Friday and Eid prayers.",
    source: "Quran 87:1",
    confidence: "high",
  },
  {
    id: "quran-096",
    pillar: "quran",
    tier: "newbie",
    difficulty: 2,
    prompt: "Which surah contains the very first verses revealed to the Prophet — 'Read in the name of your Lord who created'?",
    options: ["Al-Alaq (The Clot)", "Al-Fatihah (The Opening)", "Al-Muddaththir (The Wrapped One)", "Al-Muzzammil (The Enshrouded One)"],
    answerIndex: 0,
    explanation:
      "The first revelation was the beginning of Surah Al-Alaq (96:1-5): 'Read in the name of your Lord who created — created man from a clot.'",
    source: "Quran 96:1-5",
    confidence: "high",
  },
  {
    id: "quran-097",
    pillar: "quran",
    tier: "newbie",
    difficulty: 2,
    prompt: "Which surah describes the faces on the Day of Judgement — 'some faces, that day, will be humbled'?",
    options: ["Al-Ghashiyah (The Overwhelming)", "Abasa (He Frowned)", "Al-Mursalat (Those Sent Forth)", "At-Tariq (The Night Comer)"],
    answerIndex: 0,
    explanation:
      "Surah Al-Ghashiyah (88:2-7) describes the humbled faces of the punished and, later in the surah, the joyful faces of the people of Paradise.",
    source: "Quran 88:2-7",
    confidence: "high",
  },
  {
    id: "quran-098",
    pillar: "quran",
    tier: "newbie",
    difficulty: 2,
    prompt: "Which surah says 'Those who disbelieve among the People of the Scripture were not going to part from disbelief until clear proof came to them'?",
    options: ["Al-Bayyinah (The Clear Proof)", "Al-Kafirun (The Disbelievers)", "Al-Ma'un (The Small Kindnesses)", "Al-Fil (The Elephant)"],
    answerIndex: 0,
    explanation:
      "Surah Al-Bayyinah (98:1) states the People of the Book would not leave their ways until clear proof came — then calls them to sincere worship and prayer.",
    source: "Quran 98:1",
    confidence: "high",
  },
  {
    id: "quran-099",
    pillar: "quran",
    tier: "average",
    difficulty: 4,
    prompt: "In which surah does Allah say He sent the Prophet 'as a mercy to the worlds'?",
    options: ["Al-Anbiya (The Prophets)", "At-Tawbah (The Repentance)", "Al-Fath (The Victory)", "Al-Furqan (The Criterion)"],
    answerIndex: 0,
    explanation:
      "Quran 21:107 (Surah Al-Anbiya) declares: 'And We have not sent you except as a mercy to the worlds' — one of the most famous descriptions of the Prophet's mission.",
    source: "Quran 21:107",
    confidence: "high",
  },
  {
    id: "quran-100",
    pillar: "quran",
    tier: "average",
    difficulty: 4,
    prompt: "Which surah opens with the splitting of the moon as a sign of the approaching Hour?",
    options: ["Al-Qamar (The Moon)", "An-Najm (The Star)", "Ash-Shams (The Sun)", "At-Tariq (The Night Comer)"],
    answerIndex: 0,
    explanation:
      "Surah Al-Qamar (54:1) opens: 'The Hour has drawn near, and the moon has split.' The splitting of the moon was a miracle witnessed by the Quraysh.",
    source: "Quran 54:1",
    confidence: "high",
  },
  {
    id: "quran-101",
    pillar: "quran",
    tier: "average",
    difficulty: 4,
    prompt: "Which surah swears 'I swear by this city' — referring to Makkah, where the Prophet dwelt?",
    options: ["Al-Balad (The City)", "Al-Ma'arij (The Ascending Stairways)", "Al-Qadr (The Decree)", "At-Tin (The Fig)"],
    answerIndex: 0,
    explanation:
      "Surah Al-Balad (90:1-2) swears 'by this city' — the sacred city of Makkah, where the Prophet was free of restriction. It then addresses the striving and test of human life.",
    source: "Quran 90:1-2",
    confidence: "high",
  },
  {
    id: "quran-102",
    pillar: "quran",
    tier: "average",
    difficulty: 4,
    prompt: "Which surah consoles the Prophet with 'Did He not find you an orphan and give you shelter?'",
    options: ["Ad-Duha (The Morning Brightness)", "Al-Inshirah", "Al-Layl (The Night)", "At-Takathur (The Rivalry for Increase)"],
    answerIndex: 0,
    explanation:
      "Surah Ad-Duha (93:6) reminds the Prophet that Allah found him an orphan and sheltered him, then lists His favours — revealed to reassure him after a pause in revelation.",
    source: "Quran 93:6-8",
    confidence: "high",
  },
  {
    id: "quran-103",
    pillar: "quran",
    tier: "average",
    difficulty: 4,
    prompt: "In which surah does Allah command the believers to 'guard the prayers and the middle prayer'?",
    options: ["Al-Baqarah (The Cow)", "Al-Ankabut (The Spider)", "Al-Ma'arij (The Ascending Stairways)", "Al-Imran (The Family of Imran)"],
    answerIndex: 0,
    explanation:
      "Quran 2:238 (Surah Al-Baqarah) commands guarding the prayers and especially the 'middle prayer'. Scholars are divided on which prayer is meant, most often held to be Asr.",
    source: "Quran 2:238",
    confidence: "high",
  },
  {
    id: "quran-104",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 5,
    prompt: "In which surah does Allah speak of the Prophet turning his face to the sky, then commanding the change of the qiblah toward the Sacred Mosque?",
    options: ["Al-Baqarah (The Cow)", "Al-Hajj (The Pilgrimage)", "Al-Ma'idah (The Table Spread)", "Al-Anfal (The Spoils of War)"],
    answerIndex: 0,
    explanation:
      "Quran 2:144 (Surah Al-Baqarah) records the change of the qiblah from Jerusalem to the Sacred Mosque in Makkah: 'So turn your face toward the Sacred Mosque.'",
    source: "Quran 2:144",
    confidence: "high",
  },
  {
    id: "quran-105",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 4,
    prompt: "Which surah is named after the principle of mutual consultation (shura) among believers?",
    options: ["Ash-Shura (The Consultation)", "Al-Anfal (The Spoils of War)", "Al-Hujurat (The Chambers)", "Al-Mujadila (The Pleading Woman)"],
    answerIndex: 0,
    explanation:
      "Surah Ash-Shura (42) is named after the verse '...and whose affair is decided by mutual consultation among themselves' (42:38) — a hallmark of the Muslim community.",
    source: "Quran 42:38",
    confidence: "high",
  },
  {
    id: "quran-106",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 5,
    prompt: "In which surah does Allah promise 'And whoever relies upon Allah — then He is sufficient for him'?",
    options: ["At-Talaq (The Divorce)", "Az-Zumar (The Groups)", "Al-Muzzammil (The Enshrouded One)", "Al-Insan (The Man)"],
    answerIndex: 0,
    explanation:
      "Quran 65:3 (Surah At-Talaq) promises that whoever relies on Allah, He is sufficient for him — 'Indeed, Allah will accomplish His purpose.'",
    source: "Quran 65:3",
    confidence: "high",
  },
  {
    id: "quran-107",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 5,
    prompt: "In which surah is the Quran described as being inscribed 'in a Preserved Tablet'?",
    options: ["Al-Buruj (The Constellations)", "Al-Waqi'ah (The Event)", "Al-Hijr (The Stoneland)", "Qaf"],
    answerIndex: 0,
    explanation:
      "Surah Al-Buruj (85:21-22) says the Quran is 'in a Preserved Tablet' (lawh mahfuz) — protected from alteration and corruption.",
    source: "Quran 85:21-22",
    confidence: "high",
  },
  {
    id: "quran-108",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 5,
    prompt: "Which surah tells of the owners of a garden who withheld from the poor and were punished with its destruction overnight?",
    options: ["Al-Qalam (The Pen)", "Al-Kahf (The Cave)", "Al-Ankabut (The Spider)", "Al-Qasas (The Stories)"],
    answerIndex: 0,
    explanation:
      "Surah Al-Qalam (68:17-33) relates the parable of the garden owners who refused to give the poor their share — and woke to find their garden ruined, a lesson on giving and gratitude.",
    source: "Quran 68:17-33",
    confidence: "high",
  },
  {
    id: "quran-109",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 5,
    prompt: "In which surah does Allah say He did not send down the Quran 'that you be distressed', but as a reminder?",
    options: ["Ta-Ha", "Al-Muzzammil (The Enshrouded One)", "Al-Qalam (The Pen)", "Al-Furqan (The Criterion)"],
    answerIndex: 0,
    explanation:
      "Surah Ta-Ha (20:1-3) reassures the Prophet: 'We have not sent down to you the Quran that you be distressed, but as a reminder for those who fear Allah.'",
    source: "Quran 20:1-3",
    confidence: "high",
  },
  {
    id: "quran-110",
    pillar: "quran",
    tier: "intermediate",
    difficulty: 5,
    prompt: "In which surah does Allah say 'And the heaven We constructed with might, and indeed We are its expander'?",
    options: ["Adh-Dhariyat (The Winnowing Winds)", "Al-Baqarah (The Cow)", "Ar-Rahman (The Most Merciful)", "Al-Hijr (The Stoneland)"],
    answerIndex: 0,
    explanation:
      "Quran 51:47 (Surah Adh-Dhariyat) describes Allah expanding the universe — a verse often cited in discussions of modern cosmology. Muslims note it centuries before scientific discovery.",
    source: "Quran 51:47",
    confidence: "high",
  },
];
