import type { Question } from "@/types";

/**
 * SEERAH QUESTIONS — legitimate sources only.
 * Drawn from the established prophetic biography (Ibn Hisham / Ibn Ishaq),
 * authentic hadith collections, and the Quran itself. Items marked "review"
 * are ones where classical sources vary in minor detail and need a second pass.
 */
export const seerahQuestions: Question[] = [
  // ---- Newbie ----
  {
    id: "seerah-001",
    pillar: "seerah",
    tier: "newbie",
    difficulty: 1,
    prompt: "In which city was the Prophet Muhammad (peace be upon him) born?",
    options: ["Makkah", "Madinah", "Jerusalem", "Ta'if"],
    answerIndex: 0,
    explanation:
      "The Prophet was born in Makkah in the Year of the Elephant. He later migrated to Madinah (then Yathrib).",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-002",
    pillar: "seerah",
    tier: "newbie",
    difficulty: 2,
    prompt: "In which year is the Prophet's birth commonly placed by biographers?",
    options: ["570 CE", "600 CE", "550 CE", "585 CE"],
    answerIndex: 0,
    explanation:
      "Biographers traditionally place the Prophet's birth around 570 CE, in the Year of the Elephant, in Makkah. The year itself is approximate — some scholars suggest 571 CE — and the exact month and day are debated.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-003",
    pillar: "seerah",
    tier: "newbie",
    difficulty: 1,
    prompt: "What was the name of the Prophet's father?",
    options: ["Abdullah", "Abdul-Muttalib", "Abu Talib", "Hamzah"],
    answerIndex: 0,
    explanation:
      "His father was Abdullah ibn Abdul-Muttalib, who died before the Prophet was born. He was raised first by his grandfather, then by his uncle Abu Talib.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-004",
    pillar: "seerah",
    tier: "newbie",
    difficulty: 1,
    prompt: "What was the name of the Prophet's mother?",
    options: ["Aminah", "Khadijah", "Fatimah", "Aisha"],
    answerIndex: 0,
    explanation:
      "His mother was Aminah bint Wahb. She died when he was about six years old.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-005",
    pillar: "seerah",
    tier: "newbie",
    difficulty: 1,
    prompt: "Who was the first wife of the Prophet Muhammad (peace be upon him)?",
    options: ["Khadijah bint Khuwaylid", "Aisha bint Abi Bakr", "Hafsah bint Umar", "Sawdah bint Zam'ah"],
    answerIndex: 0,
    explanation:
      "Khadijah bint Khuwaylid, a respected merchant, was the Prophet's first wife. She was also the first person to believe in his message.",
    source: "Sahih al-Bukhari; established biography",
    confidence: "high",
  },
  {
    id: "seerah-006",
    pillar: "seerah",
    tier: "newbie",
    difficulty: 2,
    prompt: "Where did the Prophet receive his first revelation?",
    options: [
      "The cave of Hira on Mount an-Nur",
      "Inside the Kaaba",
      "The valley of Mina",
      "The home of Abu Bakr",
    ],
    answerIndex: 0,
    explanation:
      "The first revelation came while the Prophet was retreating in the cave of Hira, near Makkah. Angel Jibril brought him the opening of Surah Al-'Alaq.",
    source: "Sahih al-Bukhari 3; Quran 96:1",
    confidence: "high",
  },
  {
    id: "seerah-007",
    pillar: "seerah",
    tier: "newbie",
    difficulty: 2,
    prompt: "To which city did the Prophet migrate (perform the Hijrah) in 622 CE?",
    options: ["Madinah (Yathrib)", "Makkah", "Jerusalem", "Abyssinia"],
    answerIndex: 0,
    explanation:
      "The Hijrah took the Prophet and his followers from Makkah to Madinah (then Yathrib) in 622 CE. This event marks year one of the Islamic calendar.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },

  // ---- Average ----
  {
    id: "seerah-008",
    pillar: "seerah",
    tier: "average",
    difficulty: 3,
    prompt: "Which was the first major battle fought by the Muslims after the Hijrah?",
    options: ["Badr", "Uhud", "Khandaq (the Trench)", "Hunayn"],
    answerIndex: 0,
    explanation:
      "The Battle of Badr took place in the second year after the Hijrah (624 CE). Despite being outnumbered, the Muslims prevailed. It is mentioned in the Quran.",
    source: "Established biography; Quran 3:123",
    confidence: "high",
  },
  {
    id: "seerah-009",
    pillar: "seerah",
    tier: "average",
    difficulty: 3,
    prompt: "The Islamic calendar begins with which event?",
    options: [
      "The Hijrah (migration to Madinah)",
      "The birth of the Prophet",
      "The first revelation",
      "The conquest of Makkah",
    ],
    answerIndex: 0,
    explanation:
      "The Hijrah in 622 CE was chosen by Caliph Umar as the starting point of the Islamic calendar, making it year 1 AH (After Hijrah).",
    source: "Established Islamic history",
    confidence: "high",
  },
  {
    id: "seerah-010",
    pillar: "seerah",
    tier: "average",
    difficulty: 3,
    prompt: "Who was the first muezzin (caller to prayer) in Islam?",
    options: ["Bilal ibn Rabah", "Abu Bakr", "Umar ibn al-Khattab", "Zayd ibn Harithah"],
    answerIndex: 0,
    explanation:
      "Bilal ibn Rabah, a former enslaved man freed by Abu Bakr, was chosen as the first muezzin and is renowned for his call to prayer.",
    source: "Established biography; hadith collections",
    confidence: "high",
  },
  {
    id: "seerah-011",
    pillar: "seerah",
    tier: "average",
    difficulty: 3,
    prompt: "In which year did the Treaty of Hudaybiyyah take place?",
    options: ["6 AH", "2 AH", "8 AH", "10 AH"],
    answerIndex: 0,
    explanation:
      "The Treaty of Hudaybiyyah (6 AH) was a peace agreement between the Muslims and the Quraysh of Makkah, leading to the events of the following years.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-012",
    pillar: "seerah",
    tier: "average",
    difficulty: 3,
    prompt: "Where did the first group of Muslims migrate to, before the Hijrah to Madinah?",
    options: [
      "Abyssinia (Ethiopia)",
      "Egypt",
      "Syria",
      "Yemen",
    ],
    answerIndex: 0,
    explanation:
      "To escape persecution, a group of Muslims migrated to Abyssinia, whose just ruler (the Negus / al-Najashi) gave them refuge.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-013",
    pillar: "seerah",
    tier: "average",
    difficulty: 3,
    prompt: "Which uncle of the Prophet protected and supported him in Makkah throughout the early years?",
    options: ["Abu Talib", "Hamzah", "Al-Abbas", "Al-Harith"],
    answerIndex: 0,
    explanation:
      "Abu Talib, the Prophet's uncle, sheltered and defended him during the early years in Makkah, though he himself did not embrace Islam.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-014",
    pillar: "seerah",
    tier: "average",
    difficulty: 4,
    prompt: "The period known as the 'Year of Sorrow' is associated with the deaths of which two people close to the Prophet?",
    options: [
      "Khadijah and Abu Talib",
      "Aminah and Abdul-Muttalib",
      "Hamzah and Zayd",
      "Fatimah and Ali",
    ],
    answerIndex: 0,
    explanation:
      "In the year around 619 CE (about 10 years before the Hijrah), the Prophet lost both his wife Khadijah and his uncle Abu Talib, a period biographers call the Year of Sorrow.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },

  // ---- Intermediate ----
  {
    id: "seerah-015",
    pillar: "seerah",
    tier: "intermediate",
    difficulty: 4,
    prompt: "In which year did the conquest of Makkah take place?",
    options: ["8 AH", "6 AH", "2 AH", "10 AH"],
    answerIndex: 0,
    explanation:
      "Makkah was conquered peacefully in 8 AH (630 CE) after the Quraysh breached the Treaty of Hudaybiyyah. The Prophet declared a general amnesty.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-016",
    pillar: "seerah",
    tier: "intermediate",
    difficulty: 4,
    prompt: "According to the Quran (17:1), the Night Journey (al-Isra) traveled from Makkah to which mosque?",
    options: ["Al-Aqsa Mosque", "Masjid an-Nabawi", "Masjid Quba", "Masjid al-Haram"],
    answerIndex: 0,
    explanation:
      "The Isra took the Prophet from the Sacred Mosque to the Al-Aqsa Mosque in Jerusalem, from where the ascension (Mi'raj) to the heavens began.",
    source: "Quran 17:1; Sahih al-Bukhari",
    confidence: "high",
  },
  {
    id: "seerah-017",
    pillar: "seerah",
    tier: "intermediate",
    difficulty: 4,
    prompt: "In which year did the Prophet perform the Farewell Pilgrimage (Hajjat al-Wida)?",
    options: ["10 AH", "8 AH", "6 AH", "2 AH"],
    answerIndex: 0,
    explanation:
      "The Prophet performed his only Hajj in 10 AH (632 CE). His sermon at Arafat, known as the Farewell Sermon, laid down key rights and principles.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-018",
    pillar: "seerah",
    tier: "intermediate",
    difficulty: 4,
    prompt: "Where is the Prophet Muhammad (peace be upon him) buried?",
    options: [
      "Al-Masjid an-Nabawi, Madinah",
      "Al-Aqsa Mosque, Jerusalem",
      "The Sacred Mosque, Makkah",
      "Cave of Hira",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet died in 11 AH and was buried in the room of Aisha, within what is now the Prophet's Mosque (al-Masjid an-Nabawi) in Madinah.",
    source: "Sahih al-Bukhari; established biography",
    confidence: "high",
  },
  {
    id: "seerah-019",
    pillar: "seerah",
    tier: "intermediate",
    difficulty: 4,
    prompt: "At approximately what age did the Prophet (peace be upon him) pass away?",
    options: ["63", "60", "65", "58"],
    answerIndex: 0,
    explanation:
      "The Prophet died in 632 CE (11 AH) at about 63 lunar years of age.",
    source: "Sahih al-Bukhari; established biography",
    confidence: "high",
  },
  {
    id: "seerah-020",
    pillar: "seerah",
    tier: "intermediate",
    difficulty: 5,
    prompt: "During the Prophet's final illness, who led the congregational prayer in the mosque at the Prophet's instruction?",
    options: ["Abu Bakr as-Siddiq", "Umar ibn al-Khattab", "Ali ibn Abi Talib", "Bilal ibn Rabah"],
    answerIndex: 0,
    explanation:
      "In his final illness, the Prophet instructed that Abu Bakr lead the prayer. This is understood as a significant sign of his standing among the Companions.",
    source: "Sahih al-Bukhari",
    confidence: "high",
  },
  {
    id: "seerah-021",
    pillar: "seerah",
    tier: "intermediate",
    difficulty: 5,
    prompt: "Approximately how many military campaigns (ghazawat) did the Prophet personally lead?",
    options: ["About 27", "About 10", "About 50", "About 40"],
    answerIndex: 0,
    explanation:
      "Biographers record about 27 campaigns the Prophet personally led (ghazawat) and several dozen smaller expeditions (saraya) dispatched under Companions' command. Exact counts vary slightly between sources.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },

  // ---- Newbie expansion (established seerah, Aug 2026) ----
  {
    id: "seerah-022",
    pillar: "seerah",
    tier: "newbie",
    difficulty: 1,
    prompt: "What was the name of the Prophet's grandfather, who cared for him after his parents' deaths?",
    options: ["Abdul-Muttalib", "Abu Talib", "Abdullah", "Hamzah"],
    answerIndex: 0,
    explanation:
      "Abdul-Muttalib, chief of the Quraysh, took the orphaned Muhammad under his care. After his death, the Prophet's uncle Abu Talib continued caring for him.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-023",
    pillar: "seerah",
    tier: "newbie",
    difficulty: 2,
    prompt: "Before receiving revelation, the people of Makkah called the Prophet —",
    options: [
      "Al-Amin (the Trustworthy)",
      "Al-Hakim (the Wise)",
      "As-Siddiq (the Truthful)",
      "Al-Karim (the Generous)",
    ],
    answerIndex: 0,
    explanation:
      "Before prophethood, Muhammad (peace be upon him) was known as al-Amin, 'the trustworthy', for his honesty in trade and his role in settling the dispute over placing the Black Stone.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-024",
    pillar: "seerah",
    tier: "newbie",
    difficulty: 2,
    prompt: "Who was the wet nurse who cared for the infant Prophet among the desert Arabs?",
    options: [
      "Halimah al-Sa'diyyah",
      "Aminah bint Wahb",
      "Barakah (Umm Ayman)",
      "Hind bint Utbah",
    ],
    answerIndex: 0,
    explanation:
      "By the custom of the Quraysh, the infant Muhammad was sent to the desert, where Halimah al-Sa'diyyah of the tribe of Sa'd ibn Bakr nursed him for several years.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },

  // ---- Average expansion ----
  {
    id: "seerah-025",
    pillar: "seerah",
    tier: "average",
    difficulty: 3,
    prompt: "Which mosque, built when the Prophet arrived near Madinah, is widely regarded as the first mosque in Islam?",
    options: ["Masjid Quba", "Masjid an-Nabawi", "Masjid al-Qiblatayn", "Al-Aqsa Mosque"],
    answerIndex: 0,
    explanation:
      "On the journey to Madinah, the Prophet laid the foundation of Masjid Quba, widely considered the first mosque in Islam. Quran 9:108 mentions a mosque 'founded on piety from the first day', identified with Quba.",
    source: "Established biography (Ibn Hisham); Quran 9:108",
    confidence: "high",
  },
  {
    id: "seerah-026",
    pillar: "seerah",
    tier: "average",
    difficulty: 3,
    prompt: "In which year (AH) did the Battle of Uhud take place?",
    options: ["3 AH", "2 AH", "5 AH", "7 AH"],
    answerIndex: 0,
    explanation:
      "The Battle of Uhud took place in 3 AH (about 625 CE), roughly a year after Badr. The Muslims suffered losses after the archers left their position on the hill.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-027",
    pillar: "seerah",
    tier: "average",
    difficulty: 3,
    prompt: "Who is recorded as the first child or youth to accept Islam?",
    options: [
      "Ali ibn Abi Talib",
      "Zayd ibn Harithah",
      "Abdullah ibn Masud",
      "Sa'd ibn Abi Waqqas",
    ],
    answerIndex: 0,
    explanation:
      "Ali ibn Abi Talib, the Prophet's young cousin, was the first child to embrace Islam. Khadijah was the first woman and Abu Bakr the first free man.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-028",
    pillar: "seerah",
    tier: "average",
    difficulty: 3,
    prompt: "Who accompanied the Prophet in the cave during the Hijrah, and is described in the Quran as 'the second of the two'?",
    options: ["Abu Bakr as-Siddiq", "Ali ibn Abi Talib", "Umar ibn al-Khattab", "Zayd ibn Harithah"],
    answerIndex: 0,
    explanation:
      "On the Hijrah, Abu Bakr accompanied the Prophet; both hid in the Cave of Thawr, about which Quran 9:40 says 'Allah helped him… when he was with his companion in the cave.'",
    source: "Quran 9:40; established biography",
    confidence: "high",
  },

  // ---- Intermediate expansion ----
  {
    id: "seerah-029",
    pillar: "seerah",
    tier: "intermediate",
    difficulty: 4,
    prompt: "Approximately how many years did the Prophet spend in Madinah after the Hijrah?",
    options: ["About 10", "About 8", "About 12", "About 5"],
    answerIndex: 0,
    explanation:
      "The Prophet migrated to Madinah in 622 CE and died there in 632 CE — about 10 years — after roughly 13 years of calling to Islam in Makkah.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-030",
    pillar: "seerah",
    tier: "intermediate",
    difficulty: 4,
    prompt: "After the Year of Sorrow, to which city did the Prophet travel to invite its people to Islam, only to be rejected?",
    options: ["Ta'if", "Abyssinia", "Jerusalem", "Yathrib"],
    answerIndex: 0,
    explanation:
      "Around 620 CE the Prophet went to Ta'if seeking support and inviting its people to Islam, but was harshly rejected. It was one of the hardest moments of his mission.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-031",
    pillar: "seerah",
    tier: "intermediate",
    difficulty: 5,
    prompt: "Under the Treaty of Hudaybiyyah, Muslims were permitted to return to Makkah the following year for Umrah for how many days?",
    options: ["Three days", "One day", "Seven days", "Ten days"],
    answerIndex: 0,
    explanation:
      "The treaty allowed the Muslims to perform Umrah the following year, staying in Makkah for three days. The Prophet's party fulfilled this in 7 AH.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-032",
    pillar: "seerah",
    tier: "intermediate",
    difficulty: 4,
    prompt: "On a trade journey to Syria as a young man, the Prophet met a monk who recognised signs of his prophethood. Who was he?",
    options: ["Bahira", "Waraqah ibn Nawfal", "Salman al-Farisi", "Ka'b al-Ahbar"],
    answerIndex: 0,
    explanation:
      "On the caravan journey with his uncle Abu Talib, the monk Bahira observed signs of prophethood in the young Muhammad and advised Abu Talib to protect him. The account is recorded in Ibn Hisham's biography.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },

  // ---- Newbie expansion (established seerah, batch 2) ----
  {
    id: "seerah-033",
    pillar: "seerah",
    tier: "newbie",
    difficulty: 2,
    prompt: "How old was the Prophet when he married Khadijah (may Allah be pleased with her)?",
    options: ["About 25", "About 20", "About 35", "About 40"],
    answerIndex: 0,
    explanation:
      "The Prophet married Khadijah when he was about 25 years old. She was a respected Qurayshi merchant and is remembered as his first wife and the first to embrace Islam.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-034",
    pillar: "seerah",
    tier: "newbie",
    difficulty: 1,
    prompt: "Which angel brought the revelation of the Quran to the Prophet?",
    options: ["Jibril (Gabriel)", "Mikail (Michael)", "Israfil", "Malik"],
    answerIndex: 0,
    explanation:
      "The angel Jibril (Gabriel) brought the revelation, beginning with the first verses of Surah Al-Alaq in the Cave of Hira.",
    source: "Quran 2:97; established biography",
    confidence: "high",
  },
  {
    id: "seerah-035",
    pillar: "seerah",
    tier: "newbie",
    difficulty: 2,
    prompt: "Which of the Prophet's uncles was killed as a martyr at the Battle of Uhud?",
    options: ["Hamzah", "Al-Abbas", "Abu Talib", "Harith"],
    answerIndex: 0,
    explanation:
      "Hamzah ibn Abdul-Muttalib, the Prophet's paternal uncle, was martyred at the Battle of Uhud in 3 AH. He was known for his courage and was given the title 'Lion of Allah'.",
    source: "Sahih al-Bukhari; established biography",
    confidence: "high",
  },
  {
    id: "seerah-036",
    pillar: "seerah",
    tier: "newbie",
    difficulty: 2,
    prompt: "Which month of the Islamic calendar is the month of Hajj?",
    options: ["Dhu al-Hijjah", "Rajab", "Muharram", "Sha'ban"],
    answerIndex: 0,
    explanation:
      "The Hajj takes place in Dhu al-Hijjah, the twelfth month of the Islamic calendar, culminating on the Day of Arafah on the 9th.",
    source: "Established biography; Quran 2:196",
    confidence: "high",
  },

  // ---- Average expansion (batch 2) ----
  {
    id: "seerah-037",
    pillar: "seerah",
    tier: "average",
    difficulty: 3,
    prompt: "At approximately what age did the Prophet receive the first revelation?",
    options: ["About 40", "About 30", "About 45", "About 35"],
    answerIndex: 0,
    explanation:
      "The Prophet received the first revelation in the Cave of Hira at about 40 years of age, in roughly 610 CE.",
    source: "Sahih al-Bukhari; established biography",
    confidence: "high",
  },
  {
    id: "seerah-038",
    pillar: "seerah",
    tier: "average",
    difficulty: 3,
    prompt: "Who led the Muslim emigrants to Abyssinia, the first migration of the Muslims?",
    options: [
      "Ja'far ibn Abi Talib",
      "Umar ibn al-Khattab",
      "Hamzah ibn Abdul-Muttalib",
      "Bilal ibn Rabah",
    ],
    answerIndex: 0,
    explanation:
      "Ja'far ibn Abi Talib, a cousin of the Prophet, led the group of Muslims who migrated to Abyssinia to escape persecution in Makkah.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-039",
    pillar: "seerah",
    tier: "average",
    difficulty: 3,
    prompt: "Who was the freed slave whom the Prophet freed and raised, and who later was the only companion named in the Quran?",
    options: ["Zayd ibn Harithah", "Bilal ibn Rabah", "Salman al-Farisi", "Anas ibn Malik"],
    answerIndex: 0,
    explanation:
      "Zayd ibn Harithah was freed by the Prophet and raised in his household; he is the only companion mentioned by name in the Quran (33:37).",
    source: "Quran 33:37; established biography",
    confidence: "high",
  },
  {
    id: "seerah-040",
    pillar: "seerah",
    tier: "average",
    difficulty: 3,
    prompt: "Which of the Prophet's children outlived him, passing away a few months after his death?",
    options: ["Fatimah", "Zaynab", "Ruqayyah", "Umm Kulthum"],
    answerIndex: 0,
    explanation:
      "Fatimah, the youngest daughter, was the only child of the Prophet to outlive him; she passed away about six months after his death.",
    source: "Sahih al-Bukhari; established biography",
    confidence: "high",
  },

  // ---- Intermediate expansion (batch 2) ----
  {
    id: "seerah-041",
    pillar: "seerah",
    tier: "intermediate",
    difficulty: 4,
    prompt: "From which location did the Prophet deliver the Farewell Sermon?",
    options: ["Mount Arafat", "The Kaaba's courtyard", "Masjid an-Nabawi", "The hill of Safa"],
    answerIndex: 0,
    explanation:
      "The Prophet delivered the Farewell Sermon on the Day of Arafah, standing on Mount Arafat during the Farewell Pilgrimage in 10 AH.",
    source: "Sahih al-Bukhari; established biography",
    confidence: "high",
  },
  {
    id: "seerah-042",
    pillar: "seerah",
    tier: "intermediate",
    difficulty: 5,
    prompt: "Which verse, revealed during the Farewell Pilgrimage, announced the completion of the religion?",
    options: ["Quran 5:3", "Quran 2:185", "Quran 110:1", "Quran 33:40"],
    answerIndex: 0,
    explanation:
      "During the Farewell Pilgrimage, Quran 5:3 was revealed: 'This day I have perfected for you your religion and completed My favour upon you and have chosen for you Islam as religion.'",
    source: "Quran 5:3; established biography",
    confidence: "high",
  },
  {
    id: "seerah-043",
    pillar: "seerah",
    tier: "intermediate",
    difficulty: 4,
    prompt: "Which of the Prophet's daughters was the first to be married to Uthman, after whose death he married her sister Umm Kulthum?",
    options: ["Ruqayyah", "Zaynab", "Fatimah", "Aminah"],
    answerIndex: 0,
    explanation:
      "Ruqayyah was married to Uthman and died during the campaign of Badr; Uthman then married her sister Umm Kulthum, earning the title 'Dhun-Nurayn' (the one with two lights).",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-044",
    pillar: "seerah",
    tier: "intermediate",
    difficulty: 5,
    prompt: "Which expedition, in 9 AH, was the last major military expedition personally led by the Prophet?",
    options: ["Tabuk", "Khaybar", "The Conquest of Makkah", "Uhud"],
    answerIndex: 0,
    explanation:
      "The expedition of Tabuk in 9 AH was the last major campaign the Prophet personally led, undertaken against the gathering of the Byzantine-allied forces in the north.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-045",
    pillar: "seerah",
    tier: "newbie",
    difficulty: 2,
    prompt: "Who is recorded as the first free man to accept Islam?",
    options: ["Abu Bakr al-Siddiq", "Umar ibn al-Khattab", "Uthman ibn Affan", "Talhah ibn Ubaydullah"],
    answerIndex: 0,
    explanation:
      "Abu Bakr al-Siddiq was the first free man to embrace Islam. His conversion brought many others with him, including leading companions later given glad tidings of Paradise.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-046",
    pillar: "seerah",
    tier: "newbie",
    difficulty: 3,
    prompt: "In which cave did the Prophet and Abu Bakr hide for three days during the Hijrah?",
    options: ["The Cave of Thawr", "The Cave of Hira", "The Cave of Bani Hashim", "The Cave of Umm Jamil"],
    answerIndex: 0,
    explanation:
      "The Prophet and Abu Bakr hid in the Cave of Thawr, south of Makkah, for three days while the Quraysh searched for them. The Quran (9:40) mentions them as 'the second of the two in the cave'.",
    source: "Established biography (Ibn Hisham); Quran 9:40",
    confidence: "high",
  },
  {
    id: "seerah-047",
    pillar: "seerah",
    tier: "newbie",
    difficulty: 3,
    prompt: "What was the name of the camel that carried the Prophet during the Hijrah to Madinah?",
    options: ["Al-Qaswa", "Al-Buraq", "Al-Waqwaq", "Shahba"],
    answerIndex: 0,
    explanation:
      "The Prophet's she-camel Al-Qaswa carried him on the Hijrah. When she knelt in Madinah, the Prophet said she was guided by Allah, and the site became the location of his mosque.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-048",
    pillar: "seerah",
    tier: "newbie",
    difficulty: 2,
    prompt: "Who is generally recorded as the first person to accept Islam?",
    options: ["Khadijah bint Khuwaylid", "Abu Bakr al-Siddiq", "Ali ibn Abi Talib", "Umar ibn al-Khattab"],
    answerIndex: 0,
    explanation:
      "Khadijah, the Prophet's wife, was the first to accept Islam. Among free men the first was Abu Bakr, and among children/youths the first was Ali.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-049",
    pillar: "seerah",
    tier: "average",
    difficulty: 4,
    prompt: "Who is recorded as the first martyr of Islam, killed in the early Makkan persecution?",
    options: ["Sumayyah bint Khayyat", "Bilal ibn Rabah", "Ammar ibn Yasir", "Khabbab ibn al-Aratt"],
    answerIndex: 0,
    explanation:
      "Sumayyah, the mother of Ammar ibn Yasir, was killed by Abu Jahl during the Quraysh's persecution — the first martyr of the Muslim community. Ammar himself was tortured but survived.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-050",
    pillar: "seerah",
    tier: "average",
    difficulty: 4,
    prompt: "In which battle did the Muslims defend Madinah by digging a trench around it?",
    options: ["The Battle of the Trench (Al-Ahzab)", "The Battle of Badr", "The Battle of Uhud", "The Battle of Khaybar"],
    answerIndex: 0,
    explanation:
      "In 5 AH the Confederates (Ahzab) besieged Madinah. The Muslims dug a trench on the advice of Salman al-Farisi — the first time such a strategy was used in Arabia.",
    source: "Established biography (Ibn Hisham); Quran 33:9-27",
    confidence: "high",
  },
  {
    id: "seerah-051",
    pillar: "seerah",
    tier: "average",
    difficulty: 4,
    prompt: "Who suggested digging the trench that saved Madinah from the Confederates?",
    options: ["Salman al-Farisi", "Ali ibn Abi Talib", "Zubayr ibn al-Awwam", "Talhah ibn Ubaydullah"],
    answerIndex: 0,
    explanation:
      "Salman al-Farisi, a Persian companion who knew the trench tactic from warfare back home, suggested it, and the Prophet adopted the strategy.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-052",
    pillar: "seerah",
    tier: "average",
    difficulty: 4,
    prompt: "Who was the most prominent scribe of the revelation, later tasked with compiling the Quran into a single volume?",
    options: ["Zayd ibn Thabit", "Mu'awiyah ibn Abi Sufyan", "Abdullah ibn Mas'ud", "Ubayy ibn Ka'b"],
    answerIndex: 0,
    explanation:
      "Zayd ibn Thabit was a leading scribe who wrote down revelation for the Prophet. He later headed the committee that compiled the Quran into one mushaf under Abu Bakr and again under Uthman.",
    source: "Established biography (Ibn Hisham); Sahih al-Bukhari",
    confidence: "high",
  },
  {
    id: "seerah-053",
    pillar: "seerah",
    tier: "intermediate",
    difficulty: 5,
    prompt: "The breaking of which treaty by the Quraysh's allies led directly to the conquest of Makkah?",
    options: [
      "The Treaty of Hudaybiyyah",
      "The Treaty of Aqabah",
      "The Pact of Fudul",
      "The Treaty of Nubia",
    ],
    answerIndex: 0,
    explanation:
      "In 8 AH, the Quraysh-allied tribe of Banu Bakr attacked the Khuza'ah, breaking the Treaty of Hudaybiyyah. The Prophet then marched to conquer Makkah peacefully.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-054",
    pillar: "seerah",
    tier: "intermediate",
    difficulty: 4,
    prompt: "Which ruler tore up the Prophet's letter inviting him to Islam?",
    options: ["Khosrow II (Kisra) of Persia", "Heraclius of Byzantium", "The Negus of Abyssinia", "The Muqawqis of Egypt"],
    answerIndex: 0,
    explanation:
      "Kisra (Khosrow II) of Persia tore up the Prophet's letter in anger. Heraclius treated it with respect and inquiry; the Negus and Muqawqis responded with courtesy and gifts.",
    source: "Sahih al-Bukhari; established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-055",
    pillar: "seerah",
    tier: "intermediate",
    difficulty: 4,
    prompt: "Who was the mother of the Prophet's son Ibrahim, who died in infancy?",
    options: ["Maria al-Qibtiyya", "Khadijah bint Khuwaylid", "Sawdah bint Zam'ah", "Hafsa bint Umar"],
    answerIndex: 0,
    explanation:
      "Ibrahim, the Prophet's son who died as an infant, was born to Maria al-Qibtiyya, a gift sent to the Prophet by the Muqawqis of Egypt. He is buried in Al-Baqi' in Madinah.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-056",
    pillar: "seerah",
    tier: "intermediate",
    difficulty: 5,
    prompt: "Which two of the Prophet's uncles are recorded as having accepted Islam?",
    options: ["Hamzah and Al-Abbas", "Abu Talib and Abu Lahab", "Hamzah and Abu Talib", "Al-Abbas and Abu Lahab"],
    answerIndex: 0,
    explanation:
      "Two of the Prophet's paternal uncles are recorded as Muslims: Hamzah, who accepted Islam in about the 6th year of prophethood and was martyred at Uhud, and Al-Abbas, who accepted and was counted among the companions.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-057",
    pillar: "seerah",
    tier: "newbie",
    difficulty: 3,
    prompt: "Who was Umm Ayman (Barakah), devoted to the Prophet throughout his life?",
    options: [
      "His nursemaid who cared for him from childhood",
      "His paternal aunt",
      "His first wife's servant who married a son of the Prophet's uncle",
      "His wet nurse from the desert",
    ],
    answerIndex: 0,
    explanation:
      "Barakah, known as Umm Ayman, was the Prophet's nursemaid from childhood. She remained devoted to him all his life, and he called her 'a mother after my mother'.",
    source: "Established biography (Ibn Hisham); Sahih Muslim",
    confidence: "high",
  },
  {
    id: "seerah-058",
    pillar: "seerah",
    tier: "newbie",
    difficulty: 2,
    prompt: "In whose house did the Prophet pass away?",
    options: [
      "The house of Aisha, his wife",
      "The house of Ali ibn Abi Talib",
      "The house of Abu Bakr al-Siddiq",
      "The house of Hamzah",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet died in the house of Aisha, adjacent to his mosque in Madinah, and was buried in the same room.",
    source: "Established biography (Ibn Hisham); Sahih al-Bukhari",
    confidence: "high",
  },
  {
    id: "seerah-059",
    pillar: "seerah",
    tier: "newbie",
    difficulty: 2,
    prompt: "What did the Prophet work as in his youth, before prophethood?",
    options: ["Shepherd, then trader", "Farmer", "Blacksmith", "Scribe"],
    answerIndex: 0,
    explanation:
      "As a young man the Prophet worked as a shepherd, then as a trader — including managing Khadijah's caravan, which he did with such honesty that she proposed marriage.",
    source: "Established biography (Ibn Hisham); Sahih al-Bukhari",
    confidence: "high",
  },
  {
    id: "seerah-060",
    pillar: "seerah",
    tier: "newbie",
    difficulty: 2,
    prompt: "How many daughters did the Prophet have?",
    options: ["Four", "Three", "Two", "Five"],
    answerIndex: 0,
    explanation:
      "The Prophet had four daughters by Khadijah: Zaynab, Ruqayyah, Umm Kulthum, and Fatimah.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-061",
    pillar: "seerah",
    tier: "average",
    difficulty: 4,
    prompt: "Which companion earned the title 'the Sword of Allah' (Sayf Allah)?",
    options: ["Khalid ibn al-Walid", "Ali ibn Abi Talib", "Zubayr ibn al-Awwam", "Sa'd ibn Abi Waqqas"],
    answerIndex: 0,
    explanation:
      "Khalid ibn al-Walid, a skilled military commander who accepted Islam before the conquest of Makkah, was called 'the Sword of Allah' by the Prophet.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-062",
    pillar: "seerah",
    tier: "average",
    difficulty: 3,
    prompt: "Who was chosen as the first caliph (successor) after the Prophet's death?",
    options: ["Abu Bakr al-Siddiq", "Umar ibn al-Khattab", "Uthman ibn Affan", "Ali ibn Abi Talib"],
    answerIndex: 0,
    explanation:
      "After the Prophet's death, the Muslims chose Abu Bakr al-Siddiq as his successor (khalifah). He led the community through the wars of apostasy and the collection of the Quran.",
    source: "Established biography (Ibn Hisham); Sahih al-Bukhari",
    confidence: "high",
  },
  {
    id: "seerah-063",
    pillar: "seerah",
    tier: "average",
    difficulty: 4,
    prompt: "Which companion, wounded shielding the Prophet at Uhud, was described as 'a martyr walking upon the earth'?",
    options: ["Talhah ibn Ubaydullah", "Hamzah ibn Abdul-Muttalib", "Sa'd ibn Abi Waqqas", "Abu Ubaydah ibn al-Jarrah"],
    answerIndex: 0,
    explanation:
      "Talhah ibn Ubaydullah shielded the Prophet at Uhud, taking many wounds — including injuries to his hand that left it partly paralysed. The Prophet called him 'a martyr walking upon the earth'.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-064",
    pillar: "seerah",
    tier: "average",
    difficulty: 4,
    prompt: "After arriving in Madinah, the Prophet established a bond of 'brotherhood' (al-mu'akhah) between which two groups?",
    options: [
      "The emigrants (Muhajirun) and the helpers (Ansar)",
      "The Quraysh and the Ansar",
      "The emigrants and the Jews of Madinah",
      "The helpers and the nomads",
    ],
    answerIndex: 0,
    explanation:
      "The Prophet paired each emigrant with an Ansari 'brother', joining the Muhajirun and Ansar into one community. This brotherhood included mutual inheritance in the early years.",
    source: "Established biography (Ibn Hisham); Sahih al-Bukhari",
    confidence: "high",
  },
  {
    id: "seerah-065",
    pillar: "seerah",
    tier: "intermediate",
    difficulty: 5,
    prompt: "Who wrote down the text of the Treaty of Hudaybiyyah?",
    options: ["Ali ibn Abi Talib", "Zayd ibn Thabit", "Mu'awiyah ibn Abi Sufyan", "Abdullah ibn Mas'ud"],
    answerIndex: 0,
    explanation:
      "Ali wrote the treaty at the Prophet's dictation. When the Quraysh objected to 'Muhammad, the Messenger of Allah', the Prophet had Ali strike it out, saying he was a Messenger regardless.",
    source: "Sahih al-Bukhari; established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-066",
    pillar: "seerah",
    tier: "intermediate",
    difficulty: 4,
    prompt: "Which surah refers to the pledge of the believers under the tree at Hudaybiyyah?",
    options: ["Al-Fath (The Victory)", "Al-Mumtahanah (The Examined Woman)", "Al-Hashr (The Gathering)", "Al-Munafiqun (The Hypocrites)"],
    answerIndex: 0,
    explanation:
      "Surah Al-Fath (48:18) mentions Allah being pleased with the believers who gave their pledge (Bay'at al-Ridwan) under the tree at Hudaybiyyah. The surah was revealed after the treaty.",
    source: "Quran 48:18; established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-067",
    pillar: "seerah",
    tier: "intermediate",
    difficulty: 4,
    prompt: "Which of the Prophet's wives was the daughter of Abu Bakr al-Siddiq?",
    options: ["Aisha", "Hafsa", "Umm Salamah", "Zaynab bint Jahsh"],
    answerIndex: 0,
    explanation:
      "Aisha bint Abi Bakr was the daughter of the first caliph. She was one of the most prolific narrators of hadith and the subject of a Quranic verse clearing her of slander (24:11-20).",
    source: "Established biography (Ibn Hisham); Quran 24:11-20",
    confidence: "high",
  },
  {
    id: "seerah-068",
    pillar: "seerah",
    tier: "intermediate",
    difficulty: 5,
    prompt: "Which companion is recorded as the first to recite the Quran aloud in Makkah, despite the persecution?",
    options: ["Abdullah ibn Mas'ud", "Bilal ibn Rabah", "Ammar ibn Yasir", "Sa'd ibn Abi Waqqas"],
    answerIndex: 0,
    explanation:
      "Abdullah ibn Mas'ud recited Surah Ar-Rahman aloud at the Kaaba before a gathering of Quraysh. He was beaten for it, then retorted that he feared the disbelievers less than they feared him.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-069",
    pillar: "seerah",
    tier: "newbie",
    difficulty: 3,
    prompt: "Who was the Prophet's wife after the death of Khadijah?",
    options: ["Sawdah bint Zam'ah", "Hafsa bint Umar", "Umm Salamah", "Maymunah bint al-Harith"],
    answerIndex: 0,
    explanation:
      "Sawdah bint Zam'ah, a widow of the early Muslim emigration, was the Prophet's first wife after Khadijah. Her marriage was also an act of care for a devoted early Muslim woman.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-070",
    pillar: "seerah",
    tier: "newbie",
    difficulty: 2,
    prompt: "For roughly how many years did the Prophet call to Islam in Makkah before migrating to Madinah?",
    options: ["13 years", "5 years", "20 years", "7 years"],
    answerIndex: 0,
    explanation:
      "After receiving the first revelation at about age 40, the Prophet remained in Makkah calling to Islam for around 13 years before the Hijrah to Madinah.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-071",
    pillar: "seerah",
    tier: "newbie",
    difficulty: 2,
    prompt: "To which clan of the Quraysh did the Prophet belong?",
    options: ["Banu Hashim", "Banu Umayyah", "Banu Zuhrah", "Banu Makhzum"],
    answerIndex: 0,
    explanation:
      "The Prophet belonged to Banu Hashim, the clan of the Quraysh named after his great-grandfather Hashim. The clan included his uncle Abu Talib, who protected him.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-072",
    pillar: "seerah",
    tier: "newbie",
    difficulty: 3,
    prompt: "Which four leaders are called 'the rightly-guided caliphs' (al-khulafa al-rashidun)?",
    options: [
      "Abu Bakr, Umar, Uthman, and Ali",
      "Abu Bakr, Umar, Khalid, and Uthman",
      "Umar, Uthman, Ali, and Mu'awiyah",
      "Abu Bakr, Ali, Hamzah, and Uthman",
    ],
    answerIndex: 0,
    explanation:
      "The four rightly-guided caliphs, who ruled in succession after the Prophet's death, are Abu Bakr, Umar, Uthman, and Ali (may Allah be pleased with them).",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-073",
    pillar: "seerah",
    tier: "average",
    difficulty: 4,
    prompt: "Which companion did the Prophet describe as the most knowledgeable of his community in lawful and unlawful (halal and haram) matters?",
    options: ["Mu'adh ibn Jabal", "Ibn Abbas", "Zayd ibn Thabit", "Abu Huraira"],
    answerIndex: 0,
    explanation:
      "The Prophet said the most learned of his community in lawful and unlawful matters was Mu'adh ibn Jabal. He was also a renowned reciter and was sent to Yemen as a judge.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-074",
    pillar: "seerah",
    tier: "average",
    difficulty: 4,
    prompt: "Which companion did the Prophet call 'the trustworthy one of this community'?",
    options: ["Abu Ubaydah ibn al-Jarrah", "Talhah ibn Ubaydullah", "Sa'd ibn Abi Waqqas", "Zubayr ibn al-Awwam"],
    answerIndex: 0,
    explanation:
      "The Prophet said every community has a trustworthy guardian, and the trustworthy one of this community is Abu Ubaydah ibn al-Jarrah.",
    source: "Sahih al-Bukhari 3744",
    confidence: "high",
  },
  {
    id: "seerah-075",
    pillar: "seerah",
    tier: "average",
    difficulty: 4,
    prompt: "Which battle in 7 AH conquered the stronghold of Khaybar, a centre of opposition after the Treaty of Hudaybiyyah?",
    options: ["The Battle of Khaybar", "The Battle of Mut'ah", "The Battle of the Trench", "The Battle of Hunayn"],
    answerIndex: 0,
    explanation:
      "The Muslims besieged and conquered Khaybar in 7 AH, taking its fortified date-palm settlements. The battle also saw the famous feats of Ali in opening the fortress gate.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-076",
    pillar: "seerah",
    tier: "average",
    difficulty: 4,
    prompt: "In which battle, in 8 AH, did the Muslims first face the Byzantines, and where was Ja'far ibn Abi Talib martyred?",
    options: ["The Battle of Mut'ah", "The Battle of Hunayn", "The Battle of Tabuk", "The Battle of Yarmouk"],
    answerIndex: 0,
    explanation:
      "At Mut'ah in 8 AH, a 3,000-strong Muslim force faced a far larger Byzantine-allied army. Ja'far ibn Abi Talib was martyred there after leading the banner.",
    source: "Established biography (Ibn Hisham); Sahih al-Bukhari",
    confidence: "high",
  },
  {
    id: "seerah-077",
    pillar: "seerah",
    tier: "intermediate",
    difficulty: 4,
    prompt: "Which companion was known for his profound asceticism and simple devotion in the early community?",
    options: ["Abu Dharr al-Ghifari", "Khalid ibn al-Walid", "Uthman ibn Affan", "Mus'ab ibn Umayr"],
    answerIndex: 0,
    explanation:
      "Abu Dharr al-Ghifari was famed for his asceticism, truthfulness, and concern for the poor — the Prophet said of him that he walks alone, dies alone, and is raised alone.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-078",
    pillar: "seerah",
    tier: "intermediate",
    difficulty: 5,
    prompt: "Which companion is recorded as the first to shoot an arrow in the cause of Allah?",
    options: ["Sa'd ibn Abi Waqqas", "Uqbah ibn Amir", "Miqdad ibn al-Aswad", "Khalid ibn al-Walid"],
    answerIndex: 0,
    explanation:
      "Sa'd ibn Abi Waqqas, one of the first to accept Islam and a maternal relative of the Prophet, said: 'I was the first Arab to shoot an arrow in the cause of Allah.'",
    source: "Established biography (Ibn Hisham); Sahih al-Bukhari",
    confidence: "high",
  },
  {
    id: "seerah-079",
    pillar: "seerah",
    tier: "intermediate",
    difficulty: 4,
    prompt: "Which surah begins 'When the victory of Allah has come and the conquest' and is associated with the conquest of Makkah?",
    options: ["An-Nasr (The Divine Support)", "Al-Fath (The Victory)", "Al-Fajr (The Dawn)", "Ad-Duha (The Morning Brightness)"],
    answerIndex: 0,
    explanation:
      "Surah An-Nasr (110) — 'When the victory of Allah has come and the conquest' — was revealed around the conquest of Makkah. The Prophet took it as a sign that his mission was complete.",
    source: "Quran 110; established biography (Ibn Hisham)",
    confidence: "high",
  },
  {
    id: "seerah-080",
    pillar: "seerah",
    tier: "intermediate",
    difficulty: 5,
    prompt: "Before the Hijrah, the people of which city gave the Prophet two pledges of allegiance at Aqabah?",
    options: ["Yathrib (Madinah)", "Ta'if", "Abyssinia", "Khaybar"],
    answerIndex: 0,
    explanation:
      "Two groups from Yathrib pledged allegiance to the Prophet at Aqabah — a first pledge of 12, then a second of 75 (including two women). These pledges paved the way for the Hijrah.",
    source: "Established biography (Ibn Hisham)",
    confidence: "high",
  },
];
